CODEOWNERS
README.md
vizro-core/README.md
vizro-core/changelog.d/20230906_124139_huong_li_nguyen_update_links_owners.md
vizro-core/src/vizro/static/css/scroll_bar.css

- Update CODEOWNERS file
- Update links to authors on README
- Add in minor CSS fix for scroll bar on light theme
CSS bug fixed:
Before:

Update author links and codeowners

---

vizro-core/changelog.d/20230908_142845_huong_li_nguyen_remove_no_data_string.md
vizro-core/examples/default/app.py
vizro-core/src/vizro/models/_components/graph.py

Remove NO DATA message during graph loading

---

README.md
vizro-core/README.md
vizro-core/changelog.d/20230908_145541_maximilian_schulz_add_link_to_README.md

- move link to docs to be accessible/visible via README

Add docs link to README

---

vizro-core/changelog.d/20230908_174653_maximilian_schulz_version_bump.md
vizro-core/schemas/0.1.1.dev0.json
vizro-core/src/vizro/__init__.py

- bump version to next dev version

version bump to next dev

---

.pre-commit-config.yaml
README.md
tools/find_forbidden_words_in_repo.sh
vizro-core/README.md
vizro-core/changelog.d/20230913_134437_alexey_snigir_check_spelling_hook.md
vizro-core/docs/index.md

Pre-commit `check-spelling` hook for words `colour` and `visualisation`

Add pre-commit check-spelling hook

---

README.md
SECURITY.md
vizro-core/README.md
vizro-core/changelog.d/20230922_092912_huong_li_nguyen_update_mail.md

- Update mail address with the officially provided 
- Add security policy to README

Update security policy in README and mail address

---

.github/workflows/check-release.yml
vizro-core/changelog.d/20230922_161911_maximilian_schulz_fix_linting_release.md
vizro-core/docs/index.md
vizro-core/hatch.toml

- avoid early exit from release hatch command
- similar fix for automatic PR raised

Fix release linting

---

.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md
SECURITY.md
vizro-core/changelog.d/20230922_152625_huong_li_nguyen_replace_mail.md

- Add NOTICE to PR Template
- Add docs to issue config
- Update contact information for security again

Update PR template and issue config

---

vizro-core/changelog.d/20230925_154857_lingyi_zhang_19_37_17.md
vizro-core/schemas/0.1.3.dev0.json
vizro-core/src/vizro/__init__.py

- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

version bump after vizro-core-0.1.2

---

.github/workflows/check-release.yml
vizro-core/changelog.d/20230926_090231_maximilian_schulz_small_improvement.md

- small improvement to CI, eliminating need to lint PR
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

Small improvement to CI process of release

---

README.md
vizro-core/README.md
vizro-core/changelog.d/20230928_151157_maximilian_schulz_link_to_stable.md

- link to latest stable docs (given that we also automatically forward to them already)
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

Link to latest stable docs

---

CODEOWNERS
vizro-core/changelog.d/20231005_135142_huong_li_nguyen_update_custom_control_example.md
vizro-core/docs/pages/user_guides/components.md
vizro-core/tests/unit/vizro/models/test_page.py

- Update docs to show how to use Button as a ControlType via custom component approach
- Add unit tests for valid components/controls
Follow-up PR to this: https://github.com/mckinsey/vizro/pull/88
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

Add more unit tests for page components/controls

---

vizro-core/changelog.d/20231025_125539_huong_li_nguyen_add_disclaimer_for_custom_created.md
vizro-core/docs/pages/user_guides/custom_charts.md
vizro-core/docs/pages/user_guides/custom_components.md
vizro-core/docs/pages/user_guides/integration.md

Add disclaimer for custom created components and integrations

---

.github/workflows/check-release.yml
vizro-core/changelog.d/20231027_115356_alexey_snigir_package_check_fix.md

Fixed wrong path to the whl file

Fix for release package check

---

vizro-ai/changelog.d/20231103_161536_chiara_pullem_incorporate_e2e_feedback.md
vizro-ai/src/vizro_ai/utils/_constants.py

Remove file types to resolve safeguard issue

---

vizro-core/changelog.d/20231106_165628_antony.milne_jupyter_and_deployment.md
vizro-core/docs/pages/development/contributing.md
vizro-core/docs/pages/user_guides/integration.md
vizro-core/docs/pages/user_guides/run.md

A few corrections, clarification and additions to the docs.

Update docs on kedro integration and deployment

---

.github/workflows/checks-vizro-ai.yml
.github/workflows/checks-vizro-core.yml
.github/workflows/lint-vizro-all.yml
.github/workflows/test-integration-vizro-ai.yml
.github/workflows/test-integration-vizro-core.yml
.github/workflows/test-unit-vizro-ai.yml
.github/workflows/test-unit-vizro-core.yml
vizro-ai/changelog.d/20231109_113606_alexey_snigir_pin_openai_version.md
vizro-ai/pyproject.toml
vizro-ai/snyk/requirements.txt

openai release breaking version 1.0.0
set upper bound version for openai less then 1.0.0

Set upper bound version for openai

---

vizro-core/changelog.d/20231109_174751_joseph_perkins_vizro_core.md
vizro-core/schemas/0.1.7.dev0.json
vizro-core/src/vizro/__init__.py

version bump vizro-core 0.1.7dev

version bump vizro-core 0.1.7dev

---

vizro-core/examples/default/app.py
vizro-core/src/vizro/managers/_data_manager.py

Build on top of https://github.com/mckinsey/vizro/pull/133/commits/d6c22150bd5d58981c828deecf5993d9f231abc2
Options for configuring per-dataset arguments:
```
data_manager["gapminder"] = VizroDataSet(
retrieve_gapminder,
timeout=600,
)
data_manager["gapminder2"] = VizroDataSet(
retrieve_gapminder,
timeout=600
)
```
```
data_manager["gapminder"] = retrieve_gapminder
print("to update cache config")
data_manager["gapminder"].set_cache_config(timeout=6000)
data_manager["gapminder2"] = retrieve_gapminder
print("to update cache config")
data_manager["gapminder2"].set_cache_config(unless=lambda: True)
```
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or …

Flask caching per dataset

---

.github/workflows/check-release.yml
vizro-core/changelog.d/20231110_122219_alexey_snigir_check_release_fix.md

Bash syntax fix for checking whl file during release

check whl file fix

---

vizro-core/changelog.d/20231213_144733_huong_li_nguyen_update_demo.md
vizro-core/examples/default/app.py

- Tidy up some of the data generation code snippets
- Improve demo dashboard
- Move homepage to its own icon
- Format numbers in data table for benchmark analysis page
- Improve layout of benchmark analysis page (e.g. Add parameter, change layout, change title so it's clearer what the user can interact with)
Note: This is just a quick fix to improve the last screen of the demo dashboard. Hence, I didn't keep the yaml, dict, json examples in sync as we still need to align whether we want to keep these for this demo dashboard or not. This will be tackled in another PR after alignment on what we should do with the demo / feature compendium dashboard.
Before:
After:
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that …

Update configuration for demo dashboard

---

.github/workflows/checks-vizro-ai.yml
.github/workflows/checks-vizro-core.yml
.github/workflows/lint-vizro-all.yml
.github/workflows/test-integration-vizro-ai.yml
.github/workflows/test-integration-vizro-core.yml
.github/workflows/test-unit-vizro-ai.yml
.github/workflows/test-unit-vizro-core.yml
vizro-core/changelog.d/20231213_120926_alexey_snigir_cancel_gh_actions_fix.md
vizro-core/tests/integration/test_examples.py

It seems like the problem with this error `Canceling since a higher priority waiting request for 'branch' exists` should be solved by deleting `concurrency` setting

Fix for cancelling GitHub actions jobs

---

vizro-core/changelog.d/20231215_145925_petar_pejovic_0_1_8_dev0.md
vizro-core/schemas/0.1.8.dev0.json
vizro-core/src/vizro/__init__.py

Bump vizro-core 0.1.8.dev0 version

---

.github/workflows/release-if-needed.yml
vizro-core/changelog.d/20231218_112924_alexey_snigir_lib_check_fix.md

Fixed small bug in getting package name for the `Check correct package uploaded to PyPI` step in release process

Package name fix for release process

---

CODEOWNERS
vizro-core/changelog.d/20231222_112619_nadija_ratkusic_graca_parameter_bug.md
vizro-core/docs/pages/development/authors.md
vizro-core/examples/default/app.py
vizro-core/src/vizro/actions/_actions_utils.py
vizro-core/tests/unit/vizro/actions/test_actions_utils.py

Fixed bug on update nested graph properties. 
Issue: https://github.com/McK-Internal/vizro-internal/issues/270 …

Bug fix on update nested graph properties

---

vizro-core/changelog.d/20240104_144414_nadija_ratkusic_graca_0_1_9_dev0.md
vizro-core/schemas/0.1.9.dev0.json
vizro-core/src/vizro/__init__.py

Bump vizro-core-0.1.9.dev0

---

vizro-ai/changelog.d/20240105_101137_maximilian_schulz_0_1_2_dev0.md
vizro-ai/src/vizro_ai/__init__.py

Version bump to new dev version
- I have not added data or restricted code in any commits, …

Version bump vizro-ai to 0.1.2.dev0

---

.circleci/config.yml
.github/workflows/release-if-needed.yml
vizro-core/changelog.d/20240109_111254_alexey_snigir_fix_running_status.md

Added logic for checking `running` job status in circleci and wait for `failed` or `success`
Another small fix to the release workflow
- I have not referenced individuals, products or companies in …

Fix running status in circleci failed the tests

---

.circleci/config.yml
vizro-core/changelog.d/20240110_111807_alexey_snigir_fix_running_status.md

Added sleep between requests to circleci API.
It should help prevent closing the connection from circleci side because of big requests amount.
Also added proper logic for understanding job status
- …

Fix for CircleCI is closing connection

---

vizro-core/src/vizro/models/_components/_form.py
vizro-core/src/vizro/models/_components/container.py
vizro-core/src/vizro/models/_layout.py
vizro-core/src/vizro/models/_page.py

 Refactor injection of components into layout

---

vizro-ai/changelog.d/20240122_113617_anna_xiong_add_depdency_Pyarrow.md
vizro-ai/pyproject.toml
vizro-ai/snyk/requirements.txt
vizro-core/changelog.d/20240122_114344_anna_xiong_add_depdency_Pyarrow.md
vizro-core/pyproject.toml
vizro-core/snyk/requirements.txt

- add pyarrow dependency to fix unit test error 
```
ERROR  - DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```
- set temporary upper bound of pandas and kedro 
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or …

Temp fix dependency issues of kedro and pandas

---

vizro-core/changelog.d/20240123_093932_huong_li_nguyen_clean_up_docstrings.md
vizro-core/examples/_dev/app.py
vizro-core/pyproject.toml
vizro-core/snyk/requirements.txt
vizro-core/src/vizro/_vizro.py
vizro-core/src/vizro/actions/_callback_mapping/_callback_mapping_utils.py
vizro-core/src/vizro/models/_dashboard.py
vizro-core/src/vizro/models/_layout.py
vizro-core/src/vizro/models/types.py
vizro-core/src/vizro/static/css/layout.css
vizro-core/tests/tests_utils/asserts.py

- Fix bug on scrolling and viewport on Safari 
- Remove `MarkUpSafe` dependency (as it was there only for pen-testing, but we don't use it anywhere anymore)
- Squeezed quick tidy of docstrings in this PR as well
The issues appeared on Safari because of two properties:
- `overflow: hidden `- for context see https://teamtreehouse.com/community/overflow-hidden-not-working-in-ios-safari
- `calc(100%-Xpx)` - had to replace percentage units with viewport height. I'll double-check with @pruthvip15 whether this is the right approach, but for now it fixes the issue and doesn't seem to affect the other browsers
@l0uden  - this should fix the issue we've seen on Safari. Please double-check :) 
@nadijagraca - important to be aware of above such that we always double-check and fix before merge …

Fix scrolling and viewport bug on Safari

---

.github/workflows/release-if-needed.yml
vizro-core/changelog.d/20240125_123044_huong_li_nguyen_0_1_10dev.md
vizro-core/schemas/0.1.10.dev0.json
vizro-core/src/vizro/__init__.py

- Remove build-publish test (check for correct version being uploaded to pypi) as aligned in previous team meeting
- Version bump after vizro-core 0.1.9
- I have not referenced individuals, …

Version bump after vizro-core 0.1.9

---

README.md
vizro-ai/changelog.d/20240214_093242_anna_xiong_update_main_readme.md
vizro-ai/docs/index.md

- update main readme to include vizro-ai
- update vizro-ai index.md to follow changes in [Pull Request 306](https://github.com/mckinsey/vizro/pull/306)
- I have not referenced individuals, products …

Docs: update main readme

---

.github/workflows/test-integration-vizro-core.yml
vizro-core/changelog.d/20240222_155053_alexey_snigir_update_chromedriver_url.md

Chromedriver changed it's url for downloading …

Update chromedriver url

---

vizro-core/changelog.d/20240304_205519_maximilian_schulz_version_bump.md
vizro-core/schemas/0.1.13.dev0.json
vizro-core/src/vizro/__init__.py

[Release] Bump vizro-core to 0.1.13

---

vizro-core/changelog.d/20240312_095050_petar_pejovic_0_1_14_dev0.md
vizro-core/schemas/0.1.14.dev0.json
vizro-core/src/vizro/__init__.py

[Release] Bump vizro-core to 0.1.14.dev0

---

vizro-core/changelog.d/20240312_150737_huong_li_nguyen_replace_link_navlink.md
vizro-core/examples/_dev/app.py
vizro-core/src/vizro/models/_components/card.py
vizro-core/tests/unit/vizro/models/_components/test_card.py

Context: We need to replace components to dbc alternatives where suitable. This one simultaneously fixes a bug (navigation to external links didn't work before).
- Replace `dcc.Link` with `dbc.NavLink`
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone …

[Bug] Replace `dcc.Link` with `dbc.NavLink`

---

vizro-ai/changelog.d/20240313_180121_maximilian_schulz_update_vizro_ai_requirements.md
vizro-ai/hatch.toml
vizro-ai/pyproject.toml
vizro-ai/snyk/requirements.txt
vizro-ai/src/vizro_ai/chains/_llm_models.py

This PR relaxes the following dependencies:
- `langchain`
- `openai`
Further it exchanges the `ChatOpenAI` class to avoid deprecation.
It also adds a few lower bounds to langchain subpackages due to Snyk.
Lastly, we add `jupyter` as a dev dependency to facilitate development.
- I certify that the use of this contribution as authorized by the …

[Tidy] Update VizroAI dependencies

---

vizro-ai/changelog.d/20240313_190013_maximilian_schulz_version_bump.md
vizro-ai/src/vizro_ai/__init__.py

[Release] Bump vizro-ai to 0.1.3.dev0

---

vizro-core/changelog.d/20240326_105937_nadija_ratkusic_graca_0_1_15_dev0.md
vizro-core/schemas/0.1.15.dev0.json
vizro-core/src/vizro/__init__.py

[Release] Bump vizro-core to 0.1.15.dev0

---

vizro-ai/.readthedocs.yaml
vizro-ai/changelog.d/20240404_112532_jo_stichbury_update_build_docs_settings.md
vizro-ai/hatch.toml
vizro-ai/mkdocs.yml
vizro-core/.readthedocs.yaml
vizro-core/changelog.d/20240404_112524_jo_stichbury_update_build_docs_settings.md
vizro-core/docs/pages/tutorials/explore-components.md
vizro-core/docs/pages/tutorials/first-dashboard.md
vizro-core/docs/pages/user-guides/selectors.md
vizro-core/hatch.toml
vizro-core/mkdocs.yml
vizro-core/src/vizro/_vizro.py

I've updated the docs build settings to use `--strict` and catch any warnings as they arise.
Unfortunately, they also catch the griffe warnings in mkdocstrings. Could use some help from the engineering team with these please, all in the same file:
```text
WARNING -  griffe: src/vizro/_vizro.py:23: No type or annotation for parameter 'kwargs'
WARNING -  griffe: src/vizro/_vizro.py:70: No type or annotation for returned value 'Vizro'
WARNING -  griffe: src/vizro/_vizro.py:88: No type or annotation for parameter 'args'
WARNING -  griffe: src/vizro/_vizro.py:89: No type or annotation for parameter 'kwargs'
```
```python
class Vizro:
"""The main class of the `vizro` package."""
def __init__(self, **kwargs):
"""Initializes Dash app, stored in `self.dash`.
Args:
kwargs: Passed through to …
```

[Docs] Update build docs settings to use `--strict` 

---

vizro-ai/changelog.d/20240419_145915_jo_stichbury_fix_formatting_issue.md
vizro-ai/docs/pages/get-started/quickstart.md

I made a mistake in a merge earlier in the week as you can see [here](https://vizro.readthedocs.io/projects/vizro-ai/en/latest/pages/get-started/quickstart/#4-get-an-explanation-with-your-chart).
[This PR fixes it as you'll see from the built docs](https://vizro--428.org.readthedocs.build/projects/vizro-ai/en/428/pages/get-started/quickstart/#3-create-your-first-chart-using-vizro-ai).
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the …

[Docs] Fix an oops merge issue that broke tutorial formatting

---

vizro-core/changelog.d/20240422_095716_jo_stichbury_fix_typo.md
vizro-core/docs/pages/tutorials/explore-components.md

Addresses https://github.com/mckinsey/vizro/issues/431 and removes a single (duplicated) word.
- I …

[Docs] Fix typo in vizro-core docs

---

.github/workflows/test-integration-vizro-core.yml
vizro-core/changelog.d/20240424_150316_alexey_snigir_fix_for_apt_get.md

Workaround for this problem: https://github.com/orgs/community/discussions/120966
- I have not …

Fix `sudo apt-get update` failing

---

vizro-ai/changelog.d/20240424_120614_jo_stichbury_update_environment_text_vizroai.md
vizro-ai/docs/pages/tutorials/quickstart.md

Answers internal issue 707 (see long discussion thread on Slack) where I was receiving a response of unauthorized to Vizro-AI calls because the environment wasn't exported (despite following set up advice). I've added a section in case it affects others beyond me & @nadijagraca who also reported it.
You can see the relevant page of the build docs, with the new admonition, here: https://vizro--436.org.readthedocs.build/projects/vizro-ai/en/436/pages/tutorials/quickstart/
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is …

[Docs] Update Vizro-AI docs to explain how to export the environment to ensure API key visibility

---

vizro-ai/changelog.d/20240502_112941_lingyi_zhang_default_model.md
vizro-ai/docs/pages/user-guides/customize-vizro-ai.md
vizro-ai/src/vizro_ai/chains/_llm_models.py

- Add gpt4 turbo to the model options and docs …

[Docs] Add gpt4 turbo to the model options

---

vizro-ai/changelog.d/20240508_181644_alexey_snigir_fix_vizro_ai_tests.md
vizro-ai/tests/integration/test_example.py

After switching to new ai model response from vizro_ai became more diverse.
We should support it in tests …

[QA] Additional y axis variant in vizro_ai tests

---

CODEOWNERS

Added @lingyielia as code owner to vizro-ai. …

[Tidy] Update CODEOWNERS

---

vizro-core/changelog.d/20240522_140834_maximilian_schulz_small_tasks_941.md
vizro-core/examples/_dev/app.py
vizro-core/examples/demo/app.py
vizro-core/examples/demo/jupyter_version/app.ipynb

Small task, where we eliminate all `id` setting within the grid or table functions.
- I have not …

[Tidy] Clean-up examples where we set the id of grid and table within the function

---

vizro-core/docs/pages/examples/your-examples.md

Based on my conversation with @stichbury [here](https://github.com/mckinsey/vizro/issues/377), I would like to add this blog post to the list of community tutorials on Vizro. [This](https://medium.com/@saffand03/creating-custom-dashboards-with-vizro-a-comprehensive-guide-73c69c6f851e) is the article link.
- I certify that the use of this …

[Docs] Link medium article as an example to docs

---

vizro-core/changelog.d/20240605_210408_huong_li_nguyen_edits_kpi_dashboard.md
vizro-core/examples/kpi/README.md
vizro-core/examples/kpi/__init__.py
vizro-core/examples/kpi/app.py
vizro-core/examples/kpi/assets/css/custom.css

- Turn on pagination
- Remove scrolling from card by removing padding
- Add GIF to README as long as it's not properly deployed yet …

[Tidy] Add minor edits to KPI demo dashboard

---

vizro-core/changelog.d/20240613_163537_petar_pejovic_explain_exporting_filtered_data_for_tables.md
vizro-core/docs/pages/user-guides/actions.md
vizro-core/examples/_dev/app.py

Resolving -> https://github.com/McK-Internal/vizro-internal/issues/1005
- I have not added data or …

[Docs] Clarify what chart data will be exported

---

vizro-ai/changelog.d/20240619_104610_nadija_ratkusic_graca_vizro_ai_docs_updates.md
vizro-ai/docs/pages/user-guides/customize-vizro-ai.md

Update docs for vizro-ai model customisation …

[Docs] Update vizro-ai docs on model customisation

---

vizro-core/changelog.d/20240627_105712_maximilian_schulz_small_fix.md
vizro-core/docs/pages/user-guides/table.md

[Docs] Fix small docs error in the AgGrid formatting description

---

vizro-ai/changelog.d/20240626_224646_anna_xiong_azure_openai.md
vizro-ai/changelog.d/20240705_153310_lingyi_zhang_vizroai_models.md
vizro-ai/docs/pages/user-guides/customize-vizro-ai.md
vizro-ai/src/vizro_ai/chains/_llm_models.py

- Add model name aliases in code and docs
- update a wrong link
see https://github.com/mckinsey/vizro/issues/568
- I have not referenced individuals, products or companies in any commits, directly …

[Docs] Add OpenAI model name aliases

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/general-question.yml

Maybe not exactly docs, more like a comms issue, to make it simpler to report bugs, request features and ask questions.
I've addressed #1098 from our internal issues queue to edit the issues templates and simplify them a little.
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual …

[Docs] Update issue templates

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/general-question.yml
.github/labeler.yml
tools/check_branch_name.sh

- Reflect renamed Github labels
- Allow poc as branch name prefix
- I have not added data or …

[Tidy] Reflect renamed Github labels

---

vizro-core/changelog.d/20240711_110926_maximilian_schulz_fix_typo.md
vizro-core/docs/pages/user-guides/card-button.md

[Docs] Small docs fix

---

CODEOWNERS
vizro-core/changelog.d/20240712_090435_antony.milne_custom_icon.md
vizro-core/docs/pages/user-guides/navigation.md
vizro-core/src/vizro/models/_components/form/dropdown.py
vizro-core/tests/unit/vizro/models/_components/form/test_dropdown.py

* Add some comments and refactor `optionHeight` to use `ceil` rather than `floor` following #574 - just to make it clearer when we look back on it in future
* Update `CODEOWNERS` so we don't need @stichbury to approve all docs changes like https://github.com/mckinsey/vizro/pull/579 (but she still gets notified on all of them) - definitely needed while she's away, and probably a good thing to do longer term
* Tiny update to docs replacing `pie_chart` with `Pie Chart`
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not …

[Tidy] Various small tidyings

---

.github/workflows/circleci-trigger.yml
.github/workflows/release-if-needed.yml
.github/workflows/test-integration-vizro-ai.yml

We've decided to stop using environment for secrets.
I've delete all the env usages in actions.
- …

[CI] Delete environments for secrets

---

README.md
vizro-ai/README.md
vizro-ai/changelog.d/20240808_141634_maximilian_schulz_links_changes.md
vizro-core/changelog.d/20240808_101825_maximilian_schulz.md
vizro-core/docs/index.md
vizro-core/docs/pages/tutorials/explore-components.md
vizro-core/mkdocs.yml

Alternative to https://github.com/mckinsey/vizro/pull/621#issuecomment-2275632116
- I have not …

[Docs] Change link to vizro-ai docs to generic from latest where possible

---

vizro-core/changelog.d/20240816_142831_maximilian_schulz_update_mkdocs_dependency.md
vizro-core/hatch.toml

Update since there is not an official version on pypi: https://pypi.org/project/mkdocs-pycafe/
- I …

[Tidy] Change dependency to actual pypi release

---

.github/workflows/test-integration-vizro-ai.yml

Same as https://github.com/mckinsey/vizro/pull/667. 
See https://github.com/mckinsey/vizro/pull/667#issuecomment-2324325236 to understand why I created this PR, instead of merging the dependabot mentioned one.
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of …

[Tidy] Upgrade slack github action to 1.27.0

---

vizro-ai/changelog.d/20240909_105845_nadija_ratkusic_graca_update_dashboard_docs.md
vizro-ai/docs/pages/tutorials/quickstart-dashboard.md

Made it clearer that the build function needs to be run at the end, add full example to the code cell.  …

updating docs

---

README.md
vizro-core/README.md
vizro-core/changelog.d/20240923_132109_huong_li_nguyen_demo_last_changes.md
vizro-core/examples/visual-vocabulary/README.md
vizro-core/examples/visual-vocabulary/app.py
vizro-core/examples/visual-vocabulary/assets/css/custom.css
vizro-core/examples/visual-vocabulary/chart_groups.py
vizro-core/examples/visual-vocabulary/requirements.in
vizro-core/examples/visual-vocabulary/requirements.txt
vizro-core/tests/integration/test_examples.py

Last requested changes from J.
- Update title
- Add more spacing / remove bottom margin inside `intro-text` …

[Tidy] Add minor changes to demo visual-vocabulary

---

vizro-core/hatch.toml

Somehow this escaped #741 which got merged too soon.
- I have not added data or restricted code in …

Fix botched merge

---

vizro-ai/changelog.d/20240930_171207_lingyi_zhang_langgraph_dependency_error.md
vizro-ai/pyproject.toml

[QA] Fix the dependency error from langgraph

---

README.md
vizro-core/README.md
vizro-core/changelog.d/20241003_151515_huong_li_nguyen_update_preview_img.md

- Replace image with newly created gif by @Joseph-Perkins  ⭐ 
See: https://github.com/mckinsey/vizro/tree/docs/update-preview-img …

[Docs] Replace preview image with gif

---

vizro-core/changelog.d/20241004_220357_114536986+sylviezhang37_remove_legacy_code.md
vizro-core/docs/pages/explanation/authors.md
vizro-core/src/vizro/models/_layout.py

Fixes #721 , removing legacy __name__ = "__main__" block
- I have not added data or restricted …

[GHC] Refactor/remove legacy code 

---

.vale/styles/Microsoft/Headings.yml
vizro-core/docs/pages/explanation/authors.md

[Docs] Add exceptions to `heading.yml`

---

.github/workflows/vizro-qa-tests-trigger.yml

Because now we have no notebooks examples we can disable this trigger
- I have not added data or …

[CI] Disable notebooks tests trigger

---

tools/pycafe/create_pycafe_links.py
vizro-core/examples/scratch_dev/app.py

[CI] PyCafe

---

.github/workflows/pycafe-dashboards.yml
tools/pycafe/create_pycafe_links.py
vizro-core/examples/scratch_dev/app.py

[CI] PyCafe CI

---

tools/pycafe/create_pycafe_links.py
vizro-core/examples/scratch_dev/app.py
vizro-core/src/vizro/models/_dashboard.py

This PR is the final changes to main that are required to make PyCafe CI (status + comments) work also for external contributors! …

[CI] Final tests on main

---

tools/pycafe/create_pycafe_links.py
vizro-core/examples/scratch_dev/README2.md

[CI] Fix redundant / in file path

---

vizro-core/examples/visual-vocabulary/README.md

[Demo] Fix ViViVo README

---

vizro-core/docs/pages/explanation/authors.md

[Docs] Tidy authors page

---

.vale/styles/Microsoft/Acronyms.yml
vizro-core/docs/pages/tutorials/first-dashboard.md

[Docs] Update Vale acronyms to remove a warning about "MIT"

---

.github/workflows/release-if-needed.yml
vizro-core/changelog.d/20250205_122258_maximilian_schulz_broken_release_workflow.md

[Fix] Fix broken release workflow

---

tools/pycafe/test_pycafe_links.py
vizro-core/changelog.d/20250220_154613_maximilian_schulz_pycafe_ci.md

[Fix] Small fix to PyCafe CI

---

.github/workflows/update-static-files.yml
vizro-core/src/vizro/static/css/mantine_dates.css

[CI] Fix update static files GHA

---

tools/pycafe/pycafe_utils.py

[CI] Correct small error on CI

---

vizro-core/tests/e2e/vizro/dashboards/default/dashboard.py
vizro-core/tests/e2e/vizro/dashboards/default/dynamic_filters_data.yaml
vizro-core/tests/e2e/vizro/dashboards/default/pages/dynamic_filters_pages.py
vizro-core/tests/e2e/vizro/test_dom_elements/test_dynamic_data.py
vizro-core/tests/tests_utils/e2e/vizro/constants.py
vizro-core/tests/tests_utils/e2e/vizro/paths.py

Added tests for single and range datepicker. …

[QA] Dynamic datepicker e2e tests

---

pyproject.toml
vizro-core/pyproject.toml

[Docs] Adjust messaging

---

vizro-ai/changelog.d/20250514_114007_huong_li_nguyen_fix_failing_test_on_main.md
vizro-ai/examples/dashboard_ui/components.py

- The vizro-ai ui test on `main` was broken after merging the upgrade on dbc (where one of the arguments is deprecated), see https://github.com/mckinsey/vizro/actions/runs/14997524623/job/42135377044
- Quick fix for the tests to pass again :) …

[Fix] Replace deprecated argument in `dbc.Modal`

---

vizro-core/docs/pages/user-guides/custom-actions.md
vizro-core/docs/pages/user-guides/custom-charts.md
vizro-core/docs/pages/user-guides/custom-components.md
vizro-core/docs/pages/user-guides/custom-tables.md
vizro-core/docs/pages/user-guides/dashboard.md

- Closing https://github.com/mckinsey/vizro/issues/1131
- Added some additional code annotations where I thought it needed more explanations
- A bit of tidying whenever I saw something (e.g. remove extra space, docstrings etc.)
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual …

[Docs] Replace inline-comments with code annotations 

---

vizro-ai/docs/index.md
vizro-ai/mkdocs.yml

[Docs] Update Vizro-AI front page and menu to match Vizro core

---

vizro-core/docs/pages/explanation/faq.md

[Docs] Update FAQs to add a link to the roadmap and mention our OS license

---

vizro-core/docs/pages/tutorials/explore-components.md

- Add video link to user tutorial
- I have not added data or restricted code in any commits, …

[Docs] Add video to user tutorial

---

.github/workflows/test-unit-vizro-core-js.yml
.github/workflows/test-unit-vizro-mcp.yml
.github/workflows/test-vizro-ai-ui.yml

We have some jobs that aren't named correctly which is pretty confusing for seeing which workflows passed/failed. Hopefully this PR fixes it.
@l0uden please could you make sure that the Github settings for approved jobs updates correctly after this change so the right jobs are still specified there? 🙏 
These are the workflows that were not named correctly:
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their …

[CI] Tidy github workflow names

---

vizro-core/examples/scratch_dev/app.py
vizro-core/hatch.toml

[Chat] SSE with new action

---

vizro-core/changelog.d/20250915_164618_90609403+huong-li-nguyen_fix_header_hide.md
vizro-core/src/vizro/models/_dashboard.py

Closes https://github.com/mckinsey/vizro/pull/1393#issuecomment-3291347915 - thanks @petar-qb for checking! …

[Bug] Move hidden property inside logo container

---

vizro-mcp/docs/pages/tutorials/cursor-tutorial.md

Makes mention of similarities of Cursor and VS Code to help users of VS Code get started with this tutorial if they want something to work through. It is still a Cursor tutorial at heart though, so I have not renamed the page. Furthermore, I think we should probably create a VS Code specific example too, but this could be a video so I won't (for now) write up another example in markdown.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of …

[Docs] Update Vizro-MCP tutorial for cursor to compare with VS Code

---

vizro-mcp/changelog.d/20250929_113947_maximilian_schulz_bump_vizro_mcp.md
vizro-mcp/pyproject.toml
vizro-mcp/src/vizro_mcp/_utils/prompts.py
vizro-mcp/src/vizro_mcp/server.py
vizro-mcp/uv.lock

Tiny change - see title
- I have not added data or restricted code in any commits, directly or …

[Feat] Upgrade MCP to use >=0.1.46 and improve `set_control` prompting
