mckinsey/vizro

- .circleci/config.yml
- vizro-core/changelog.d/20230905_144846_alexey_snigir_change_qa_repo_name.md
Changed the name for the qa repo because it was moved to the new repo with appropriate name
> Change qa repo name to vizro-qa

- vizro-core/changelog.d/20230906_093501_huong_li_nguyen_add_table_template.md
- vizro-core/src/vizro/_themes/_templates/template_dark.py
- vizro-core/src/vizro/_themes/_templates/template_light.py
- Add template for go table if someone were to use a custom go table (otherwise table will be white on dark theme etc.)
```
@capture("graph")
def table(data_frame):
fig = go.Figure(data=[go.Table(header=dict(values=['A Scores', 'B Scores']),
cells=dict(values=[[100, 90, 80, 90], [95, 85, 75, 95]]))
])
return fig
```
> Add template for go table

- vizro-core/changelog.d/20230908_110632_huong_li_nguyen_add_test_action_validator_factory.md
- vizro-core/tests/unit/vizro/models/_components/conftest.py
- vizro-core/tests/unit/vizro/models/_components/form/test_checklist.py
- vizro-core/tests/unit/vizro/models/_components/form/test_dropdown.py
- vizro-core/tests/unit/vizro/models/_components/form/test_radioitems.py
- vizro-core/tests/unit/vizro/models/_components/test_button.py
- Consolidate tests for `action_validator_factory` after several duplications, see this thread: https://github.com/mckinsey/vizro/pull/14#discussion_r1319517169
- Rewrote already existing test for `Button` to follow same test
Essentially, we shouldn't configure the components with an action function, that doesn't make much sense to be used in that component. It's safer to use a test function such that we can still replicate the behaviour.
> Consolidate tests for action_validator_factory

- .github/dependabot.yml
- SECURITY.md
- vizro-core/changelog.d/20230921_201427_huong_li_nguyen_enable_dependabot.md
- Add security policy, see: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository
- Add dependabot.yml to enable Dependabot version updates, see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> Add security policy and config for dependabot

- pyproject.toml
- vizro-core/changelog.d/20230926_113052_maximilian_schulz_introduce_coverage.md
- vizro-core/pyproject.toml
- move coverage settings to package `pyproject.toml` (they weren't doing anything before)
- slight adjustments and introduction of minimum coverage
- set minimum coverage to **82%**
**Note**
- Took out tests from coverage, as I personally find it more misleading than helpful, it dilutes the true coverage (83% without tests vs 97% with tests)
However, it was interesting to see that some tests seem to not be executed (when running coverage on test files as well), this needs further investigation (created a ticket)
- I certify that (a) this contribution is my original …
> Introduce coverage settings and failure threshold

- vizro-core/changelog.d/20230926_173346_huong_li_nguyen_remove_left_side.md
- vizro-core/docs/pages/development/authors.md
- vizro-core/src/vizro/models/_page.py
- vizro-core/tests/unit/vizro/models/test_page.py
- Remove left_side container by default if no content present (no dashboard_title, controls, single page)
Example Code:
```
import os
import vizro.plotly.express as px
from vizro import Vizro
import vizro.models as vm
df = px.data.iris()
page = vm.Page(
title="My first dashboard",
components=[
vm.Graph(id="scatter_chart", figure=px.scatter(df, x="sepal_length", y="petal_width", color="species")),
vm.Graph(id="hist_chart", figure=px.histogram(df, x="sepal_width", color="species")),
],
)
dashboard = vm.Dashboard(pages=[page])
if __name__ == "__main__":
Vizro._user_assets_folder = os.path.abspath("../assets")
Vizro().build(dashboard).run()
```
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so …
> Remove `left_side` container by default if no content present

- vizro-core/changelog.d/20231024_101744_antony.milne_captured_callable.md
- vizro-core/src/vizro/models/types.py
- vizro-core/tests/unit/vizro/models/test_types.py
#114 uncovered a bug with `CapturedCallable`. In short, this would work ok:
```
function = lambda **kwargs: kwargs["a"]
CapturedCallable(function)(a=2) # a=2 only provided at runtime
```
And this would not:
```
CapturedCallable(function, a=2)() # a=2 is provided upfront
```
Now they should both work ok.
We have already had a couple of very small bugs that I've known about for a while, where the following sorts of functions do not work with `CapturedCallable`:
1. a function with variadic positional args like `def function(*args)`
2. a function with positional-only arguments like `def function(a, /)`
Fixing the new `**kwargs` bug, which is an important case, makes it much harder to fix these much less important cases, and so I've decided to just not support them at all. There's now an …
> Fix CapturedCallable to work better with kwargs

- .github/workflows/check-release.yml
- .github/workflows/lint-vizro-core.yml
- vizro-core/changelog.d/20231025_154920_antony.milne_scriv.md
- vizro-core/docs/pages/development/contributing.md
- vizro-core/hatch.toml
Just some very minor tidying of the changelog and release process.
The only thing that matters here is that the command `hatch run docs:changelog` is now `hatch run changelog:add`. This is due to separating the `scriv` environment into its own new one to make adding to the changelog as quick and easy as possible (e.g. for someone who just correct a typo but doesn't want to install all the docs dependencies).
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this …
> Tidy changelog and release process

- vizro-core/changelog.d/20231031_111125_huong_li_nguyen_fix_table_overflow.md
- vizro-core/src/vizro/models/_components/graph.py
- vizro-core/src/vizro/models/_components/table.py
- vizro-core/src/vizro/static/css/layout.css
- vizro-core/tests/unit/vizro/models/_components/test_graph.py
- vizro-core/tests/unit/vizro/models/_components/test_table.py
- Prevent `Table` from overflowing its container caused by `dcc.Loading` missing `parent_className`
Before:
After:
> Prevent `Table` from overflowing its container

- vizro-core/changelog.d/20231113_103808_antony.milne_prep_release.md
- vizro-core/hatch.toml
Just fixing the minor linting niggles of the release process shown in #155.
Linting commands which have non-zero exit codes will no longer prevent the rest of the scripts from running, and the CHANGELOG.md will now come already linted. …
> Fix linting of release process

- vizro-core/changelog.d/20231114_095856_petar_pejovic_fix_sliders_incorrect_input.md
- vizro-core/src/vizro/static/js/models/range_slider.js
- vizro-core/src/vizro/static/js/models/slider.js
Fixed `vm.Slider` and `vm.RangeSlider` to work with incorrect text input.
Example on the `main` branch:
https://github.com/mckinsey/vizro/assets/108530920/455e6d69-beb3-43d5-a4b4-50eef5900f94
Example on the `bugs/fix_sliders_incorrect_input` branch:
https://github.com/mckinsey/vizro/assets/108530920/bf884f34-ec3e-4d9a-bfec-80b399229745
- I certify …
> Fix vm.Slider and vm.RangeSlider to work with incorrect textual input

- .github/workflows/checks-vizro-ai.yml
- .github/workflows/checks-vizro-core.yml
- .github/workflows/lint-vizro-all.yml
- .github/workflows/release-if-needed.yml
- .github/workflows/secret-scan.yml
- .github/workflows/test-integration-vizro-ai.yml
- .github/workflows/test-integration-vizro-core.yml
- .github/workflows/test-unit-vizro-ai.yml
- .github/workflows/test-unit-vizro-core.yml
#192 renamed some jobs, which now makes it basically impossible to refer to them as required jobs in the Github settings.
This PR should fix this so that they all have sensible names again...
> Fix Github actions job names

- vizro-core/changelog.d/20231208_092136_lingyi_zhang_dash_lowerbound.md
- vizro-core/hatch.toml
- vizro-core/pyproject.toml
- vizro-core/snyk/requirements.txt
This bump is required by a chain of dependency upgrade.
- The `werkzeug` version has recently been bumped in dash 2.14.1
https://github.com/plotly/dash/pull/2674/files
- We pinned the `werkzeug` version to avoid a security venerability 
- https://github.com/mckinsey/vizro/pull/128
- https://github.com/plotly/dash/issues/2673
- I certify that the …
> Bump dash lower bound to 2.14.1

- vizro-core/changelog.d/20231218_204302_antony.milne_improve_dashboard_title.md
- vizro-core/docs/pages/user_guides/dashboard.md
- vizro-core/examples/default/app.py
- vizro-core/schemas/generate.py
- vizro-core/src/vizro/_vizro.py
- vizro-core/src/vizro/models/_dashboard.py
- vizro-core/tests/unit/vizro/conftest.py
- vizro-core/tests/unit/vizro/models/_navigation/conftest.py
- vizro-core/tests/unit/vizro/models/test_dashboard.py
Small precursor to #185, mentioned as part of #176.
When `Dashboard.title` is specified we now include it in the page title in the dash registry. This makes no difference to anything on the screen other than the `<title>` tag and a meta tag. These are useful to get right because it means that the title of the page is much more meaningful in your browser window, when you try to bookmark a dashboard, and if you share a link of a Vizro dashboard that gets previewed e.g. on social media.
- I certify that (a) this contribution is my original creation and / or (b) to the …
> Improve dashboard title

- vizro-core/changelog.d/20231222_091555_huong_li_nguyen_fix_invisible_button.md
- vizro-core/src/vizro/static/css/card.css
- If a large image is provided the invisible button inside the `Card` is not positioned correctly and can lead to unnecessary scrolling and missing areas for clicking
The invisible Button should now cover the entire area of the Card: …
> Fix position of invisible button inside `Card`

- vizro-core/changelog.d/20240102_064659_amward_update_docs_meta_tags.md
- vizro-core/docs/pages/development/contributing.md
- vizro-core/docs/pages/user_guides/assets.md
- vizro-core/docs/pages/user_guides/dashboard.md
- vizro-core/docs/pages/user_guides/pages.md
> update docs for meta tags feature

- vizro-core/changelog.d/20240109_140626_huong_li_nguyen_use_ctx_short.md
- vizro-core/src/vizro/actions/_actions_utils.py
- vizro-core/tests/unit/vizro/actions/test_export_data_action.py
- vizro-core/tests/unit/vizro/actions/test_filter_action.py
- vizro-core/tests/unit/vizro/actions/test_filter_interaction_action.py
- vizro-core/tests/unit/vizro/actions/test_on_page_load_action.py
- vizro-core/tests/unit/vizro/actions/test_parameter_action.py
- vizro-core/tests/unit/vizro/models/_components/test_graph.py
- Small clean-up PR to use `ctx` instead of `callback_context` consistently to be less verbose and use official abbreviations, see [here](https://community.plotly.com/t/dash-2-4-released-improved-callback-context-clientside-callback-promises-typescript-components-minor-ticks-and-more/64203) 
Note: ctx shortcut currently doesn't exist for `dash_clientside` yet, so there we would use the old syntax. However, with this [recent PR](https://github.com/plotly/dash/pull/2695) on Dash that got merged (but not released), we should be able to replace something like:
`window.dash_clientside.callback_context.triggered[0].prop_id.split('.')[0]` with
`window.dash_clientside.callback_context.trigger_id` in the future if we upgrade to the latest Dash version
- I submit this contribution under the [Apache …
> Apply `ctx` abbreviation consistently

- vizro-core/changelog.d/20240109_183336_huong_li_nguyen_warning_bootstrap.md
- vizro-core/docs/pages/user_guides/assets.md
- vizro-core/docs/pages/user_guides/custom_components.md
- Add warning about incompatibility with `dbc.themes`, see this issue: https://github.com/mckinsey/vizro/issues/235
- Add warning about using dbc components (if required CSS media queries are not inside assets folder)
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property …
> Add warnings about incompatibility with dbc.themes

- vizro-ai/changelog.d/20240118_144903_anna_xiong_load_env_automatically.md
- vizro-ai/docs/pages/tutorials/explore_vizro_ai.md
- vizro-ai/docs/pages/tutorials/quickstart.md
- vizro-ai/docs/pages/user_guides/api_setup.md
- vizro-ai/docs/pages/user_guides/run_vizro_ai.md
- vizro-ai/src/vizro_ai/__init__.py
**Fearure: when vizro-ai is imported, we load `.env` in the same directory where the program is run.** 
limitation: 
- The load_dotenv function, by default, searches for .env files starting from the current directory and moving upwards, as detailed in the [python-dotenv documentation](https://saurabh-kumar.com/python-dotenv/reference/). This search behavior is typically sufficient for most projects.
-  User can overwrite the default import of .env manually as below:
```
env_file = join(dirname(__file__), '.env')
env_file = find_dotenv(".env.dev")
load_dotenv(env_file)
```
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as …
> Feature: load env automatically

- pyproject.toml
- vizro-ai/changelog.d/20240122_112645_antony.milne_enable_containers_AM.md
- vizro-ai/pyproject.toml
- vizro-ai/snyk/requirements.txt
- vizro-core/changelog.d/20240122_112645_antony.milne_enable_containers_AM.md
- vizro-core/pyproject.toml
- vizro-core/snyk/requirements.txt
A proper fix following https://github.com/mckinsey/vizro/pull/274:
* remove the `pyarrow` dependency - this is not something we want to specify as a dependency. Instead what we should do is ignore the deprecation warning from pandas (which was confusingly written so made it sound like we should add `pyarrow` as a dependency)
* remove upper pin for `kedro` and `pandas`. Our kedro test broke with the release of 0.19.2 due to https://github.com/kedro-org/kedro/pull/3451 and is fixed by adding `kedro-datasets` as a dependency
Also:
* moved some dependencies pinned by Snyk to optional ones since they only come about from `kedro`. These should never have been in the core dependencies, and actually it highlights a fundamental flaw in the use of Snyk that we shouldn't be responsible for …
> Remove pin and pyarrow dependency

- .pre-commit-config.yaml
- .stylelintrc
- vizro-ai/changelog.d/20240221_181059_huong_li_nguyen_apply_alphabetical_css_order.md
- vizro-ai/docs/stylesheets/extra.css
- vizro-core/changelog.d/20240221_180436_huong_li_nguyen_apply_alphabetical_css_order.md
- vizro-core/docs/stylesheets/extra.css
- vizro-core/examples/_dev/assets/css/custom.css
- vizro-core/examples/demo/assets/css/custom.css
- vizro-core/examples/features/assets/css/custom.css
- vizro-core/src/vizro/static/css/accordion.css
- vizro-core/src/vizro/static/css/checklist.css
- vizro-core/src/vizro/static/css/collapse.css
- vizro-core/src/vizro/static/css/container.css
- vizro-core/src/vizro/static/css/dropdown.css
- vizro-core/src/vizro/static/css/index.css
- vizro-core/src/vizro/static/css/layout.css
- vizro-core/src/vizro/static/css/radio_item.css
- vizro-core/src/vizro/static/css/selectors.css
- vizro-core/src/vizro/static/css/slider.css
- vizro-core/src/vizro/static/css/table.css
- vizro-core/src/vizro/static/css/toggle.css
- vizro-core/src/vizro/static/css/token_names.css
- vizro-core/src/vizro/static/css/typography.css
- vizro-core/src/vizro/static/css/user_input.css
- Applies stylelint in pre-commit hooks: https://stylelint.io/user-guide/rules
- We follow the rules of the standard stylelint config : https://github.com/stylelint/stylelint-config-standard/blob/main/index.js
- Some rules I have overwritten - you can read more about them here: https://stylelint.io/user-guide/rules:
-  **order/properties-alphabetical-order**:  Make alphabetical sorting the default
-  **selector-class-pattern**: Prevent underscores in classNames to be raised as errors
-  **custom-property-pattern:** Prevent mantine classNames and mkdocs classNames to be raised as errors
-  **color-function-notation:** Allow standard rgba syntax
-  **alpha-value-notation:** Allow standard rgba syntax
-  **color-hex-length:** Converts everything to long syntax
-  **selector-not-notation:** …
> Configure CSS linter `stylelint`

- vizro-core/changelog.d/20240221_121749_jo_stichbury_create_style_guide.md
- vizro-core/docs/pages/development/documentation-style-guide.md
- vizro-core/mkdocs.yml
This is part of the work to apply a light edit and consistency check to docs. I've created a page with a lightweight guide for us to agree upon before I start editing.
[You can read it here!](https://vizro--325.org.readthedocs.build/en/325/pages/development/documentation-style-guide/)
I've created a separate issue to install Vale (which is a text linter) to check text changes in CI and catch when the guidelines are not observed. This isn't urgent but a nice-to-have.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not …
> Create a documentation style guide to apply across docs

- vizro-core/changelog.d/20240226_100408_huong_li_nguyen_fix_css_grid.md
- vizro-core/src/vizro/static/css/card.css
- vizro-core/src/vizro/static/css/layout.css
Noticed two bugs which are fixed by this PR:
- `page-main` not overflowing correctly in mobile mode
- `card-link` not extending properly in mobile mode
@l0uden - we should probably have some screenshot tests for the mobile layouts as well. So far I've been manually checking every week as I know there are currently other priorities, but would be good to add this to the next sprint 🙏 
**Before:**
**`page-main` not overflowing correctly in mobile mode**
**`card-link` not extending properly in mobile mode**
- I certify that (a) this contribution is my original creation …
> [Bug] Fix CSS on `page-main` in mobile layouts

- vizro-core/changelog.d/20240226_181547_huong_li_nguyen_add_selectors.md
- vizro-core/examples/features/app.py
- vizro-core/examples/features/yaml_version/app.py
- vizro-core/examples/features/yaml_version/dashboard.yaml
- vizro-core/schemas/0.1.12.dev0.json
- vizro-core/src/vizro/models/_components/form/_text_area.py
- vizro-core/src/vizro/models/_components/form/_user_input.py
- vizro-core/src/vizro/models/_components/form/checklist.py
- vizro-core/src/vizro/models/_components/form/dropdown.py
- vizro-core/src/vizro/models/_components/form/radio_items.py
- vizro-core/src/vizro/models/_components/form/range_slider.py
- vizro-core/src/vizro/models/_components/form/slider.py
- vizro-core/src/vizro/static/css/table.css
- Adds a page with all selectors in the control panel on the left (as Filter only) to the features demo dashboard
- Consolidates all docstrings inside selectors
- Fix CSS for table pagination
- I …
> [Demo] Update features example dashboard with selectors

- vizro-core/changelog.d/20240304_123956_huong_li_nguyen_add_upper_limit.md
- vizro-core/pyproject.toml
- vizro-core/snyk/requirements.txt
See this for context: https://github.com/plotly/dash/issues/2778
This is supposed to be a temporary solution only such that merging PRs is not blocked. Still waiting for feedback from @l0uden or dash
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone …
> [Bug] Set upper limit on `dash` temporarily

- .github/workflows/release-if-needed.yml
- vizro-core/changelog.d/20240315_173651_alexey_snigir_push_to_main_vizro_ai_support.md
Vizro-ai doesn't support `hatch run schema` command. 
Change version-bump step to support it.
- I …
> Vizro-ai support in version-bump step

- vizro-core/changelog.d/20240328_163211_petar_pejovic_actions_assert_component_equal_tests.md
- vizro-core/tests/unit/vizro/actions/_action_loop/test_get_action_loop_components.py
- vizro-core/tests/unit/vizro/actions/_callback_mapping/test_get_action_callback_mapping.py
- vizro-core/tests/unit/vizro/models/_action/test_action.py
- vizro-core/tests/unit/vizro/models/_controls/test_filter.py
- vizro-core/tests/unit/vizro/models/_controls/test_parameter.py
- vizro-core/tests/unit/vizro/models/test_dashboard.py
- vizro-core/tests/unit/vizro/models/test_page.py
`assert_component_equal` is implemented in the following test files:
- test_get_action_loop_components.py
- test_get_action_callback_mapping.py
- test_action.py
- test_dashboard.py
- test_filter.py
- test_parameter.py
Here is the ticket for reference -> https://github.com/McK-Internal/vizro-internal/issues/546
- I certify that the use of this …
> [QA] Using assert_component_equal in actions, dashboard and controls tests

- .pre-commit-config.yaml
- vizro-core/changelog.d/20240405_103212_antony.milne_fix_mypy.md
#397 bumped our pre-commit mypy from 1.8.0 to 1.9.0, which seemed to flag new errors that were still there even after reversion to 0.18.0 in #403.
The reason for these new errors was **not** actually the change to mypy version but that there was a new pydantic release at about the same time. Pinning the pydantic version used by mypy fixes this.
There is no caching in our CI. There is caching on pre-commit.ci but it works well and will always be running the correct version specified in our .pre-commit-config.yaml. So both our CI and pre-commit.ci are still perfect sources of truth and working correctly. Behaviour locally should be the identical to these, but just in case it's not then `pre-commit clean` should fix it by clearing your local cache.
- I submit this contribution under the …
> [CI] Fix mypy linting

- vizro-core/changelog.d/20240409_110318_huong_li_nguyen_replace_label.md
- vizro-core/src/vizro/models/_components/form/_text_area.py
- vizro-core/src/vizro/models/_components/form/_user_input.py
- vizro-core/src/vizro/models/_components/form/checklist.py
- vizro-core/src/vizro/models/_components/form/date_picker.py
- vizro-core/src/vizro/models/_components/form/dropdown.py
- vizro-core/src/vizro/models/_components/form/radio_items.py
- vizro-core/src/vizro/models/_components/form/range_slider.py
- vizro-core/src/vizro/models/_components/form/slider.py
- vizro-core/src/vizro/static/css/bootstrap_overwrites.css
- vizro-core/tests/unit/vizro/models/_components/form/test_checklist.py
- vizro-core/tests/unit/vizro/models/_components/form/test_date_picker.py
- vizro-core/tests/unit/vizro/models/_components/form/test_dropdown.py
- vizro-core/tests/unit/vizro/models/_components/form/test_radio_items.py
- vizro-core/tests/unit/vizro/models/_components/form/test_range_slider.py
- vizro-core/tests/unit/vizro/models/_components/form/test_slider.py
- vizro-core/tests/unit/vizro/models/_components/form/test_text_area.py
- vizro-core/tests/unit/vizro/models/_components/form/test_user_input.py
**Context:** This will be one of many PRs where I gradually replace our existing components with dbc equivalents (as long as functionality is the same). Simultaneously, I will always encode the relevant SASS code for our official Bootstrap theme, so everything that is temporarily added to overwrite Bootstrap can then be removed as soon as we replace the underlying source Bootstrap CSS file.
- Replace `html.Label` with `dbc.Label`
- Add temporary CSS overwrite
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my …
> [Tidy] Replace `html.Label` with `dbc.Label`

- vizro-core/changelog.d/20240412_082253_antony.milne_add_data_manager_warning.md
- vizro-core/docs/pages/user-guides/data.md
https://github.com/mckinsey/vizro/pull/398 was merged when it was failing Snyk licence and security checks. I discussed this with @Joseph-Perkins and agreed we should ignore all the warnings but also add a note to our docs - done here.
I've thoroughly read up on the security issue and am not concerned as things stand. So long as dashboard developers use trusted data then all is well. If we ever allow _untrusted_ users to upload data (e.g. through the dashboard) then we'd have to be much more careful though, since potentially that could be a big security risk that allows arbitrary code execution.
So next steps are:
1. Merge this PR
2. Ignore the snyk licence issues
3. Ignore the snyk flask-caching issue
- I submit this contribution under the [Apache 2.0 …
> [Docs] Add security warning on data manager cache

- vizro-core/changelog.d/20240416_134105_alexey_snigir_ignore_pytest_thread_warning.md
- vizro-core/tests/integration/test_examples.py
Ignoring `pytest.PytestUnhandledThreadExceptionWarning` in the integration tests as it is flaky right now and this warning doesn't affect anything
- I have not referenced individuals, products or …
> [QA] Ignore `pytest.PytestUnhandledThreadExceptionWarning`

- vizro-ai/changelog.d/20240501_111259_anna_xiong_langchian_verison_upperbound.md
- vizro-ai/pyproject.toml
- vizro-ai/snyk/requirements.txt
- vizro-ai/src/vizro_ai/__init__.py
- The class `LLMChain` is deprecated in LangChain 0.1.17 and will be removed in 0.3.0.  
- Now langchain is at 0.1.17 version so it's safe to pin upper bound and ignore warnings, given there would still be some time for 0.3.0 to be released.
- Here is a ticket created in backlog to resolve it and update LLMChain class:
update all vizro-ai base components for upper langchain version [#776](https://github.com/McK-Internal/vizro-internal/issues/776)
error msg in ci:
https://github.com/mckinsey/vizro/actions/runs/8910243758/job/24469126587
****
- I certify that (a) this …
> [Tidy] Update langchain upper bound

- vizro-core/docs/index.md
- vizro-core/docs/pages/examples/examples.md
- vizro-core/docs/pages/explanation/contributing.md
- vizro-core/docs/pages/explanation/faq.md
- vizro-core/docs/pages/tutorials/first-dashboard.md
- vizro-core/mkdocs.yml
Following discussion with @antonymilne 
* Add a link to the user examples from the main examples page, in case people don't spot the user examples page (which requires them to understand how the left hand nav works). By adding a section with a title, it brings it into the RHS table of contents, so more obvious.
* Add a mention of Plotly community forums. Have I got the right category @antonymilne ?
* TBH that whole contribution guide needs a solid revision and I have this on my list, just not yet, so if it makes sense to do so, I can park this change for now and add it in later. Alternatively, we could put something about these forums behind a "Got a question?" link on the front page of the docs, and point straight through to the Plotly forums there, so it's really obvious. LMK if you'd …
> [Docs] Two small docs changes for improved usability

- vizro-ai/.readthedocs.yaml
- vizro-ai/changelog.d/20240513_162508_antony.milne_add_link_checker.md
- vizro-ai/hatch.toml
- vizro-core/.readthedocs.yaml
- vizro-core/changelog.d/20240513_162501_antony.milne_add_link_checker.md
- vizro-core/docs/index.md
- vizro-core/docs/pages/explanation/documentation-style-guide.md
- vizro-core/hatch.toml
Add a link checking step to the build of both vizro-ai and vizro-core docs on RTD. There's no good tool built into mkdocs for this, but https://github.com/linkchecker/linkchecker works quite well here and seems fast enough.
We now have three scripts that can be run in the docs environment:
```
hatch run docs:serve 
hatch run docs:build
hatch run docs:link-check
```
@stichbury I've fixed/ignored all the errors I found apart from this one, where I can't find an authoritative-looking link to the INCITS guidelines that actually works. Please can you suggest something?
```
URL        `https://standards.incits.org/apps/group_public/download.php/131246/eb-2021-00288-001-INCITS-Inclusive-Terminology-Guidelines.pdf'
Name       `INCITS Inclusive Terminology Guidelines'
Parent URL …
```
> [Docs] Add link checker for docs

- vizro-core/changelog.d/20240515_133813_petar_pejovic_fixing_dash_table_dropdown_menu.md
- vizro-core/examples/_dev/app.py
- vizro-core/src/vizro/tables/_dash_table.py
- vizro-core/tests/unit/vizro/tables/test_dash_table.py
Solving https://github.com/McK-Internal/vizro-internal/issues/934
Run the `_dev/examples/app.py` example from the `main` and `bug/fixing_dash_table_dropdown_menu` branches to see the difference when trying to open a table dropdown cell. …
> [BUG] Fixing dash_data_table dropdown menu to open on click

- vizro-ai/changelog.d/20240522_095814_anna_xiong_vizro_ai_faq_links.md
- vizro-ai/docs/pages/explanation/disclaimer.md
- vizro-ai/docs/pages/explanation/faq.md
- vizro-ai/docs/pages/user-guides/run-vizro-ai.md
fix links missing in docs:
```
INFO    -  Doc file 'pages/explanation/disclaimer.md' contains a link './faq.md#which-llms-are-supported-by-vizro-ai', but the doc 'pages/explanation/faq.md' does not contain an anchor '#which-llms-are-supported-by-vizro-ai'.
INFO    -  Doc file 'pages/user-guides/run-vizro-ai.md' contains a link '../user-guides/install.md#large-language-model', but the doc 'pages/user-guides/install.md' does not contain an anchor '#large-language-model'.
```
- I certify that (a) this contribution is my original creation and / or (b) to the extent it …
> [Docs]fix vizro ai doc links

- vizro-core/changelog.d/20240523_085359_amward_update_dcc_loading.md
- vizro-core/hatch.toml
- vizro-core/pyproject.toml
- vizro-core/snyk/requirements.txt
- vizro-core/src/vizro/models/_components/ag_grid.py
- vizro-core/src/vizro/models/_components/graph.py
- vizro-core/src/vizro/models/_components/table.py
- vizro-core/tests/unit/vizro/models/_components/test_ag_grid.py
- vizro-core/tests/unit/vizro/models/_components/test_graph.py
- vizro-core/tests/unit/vizro/models/_components/test_table.py
- vizro-core/tests/unit/vizro/tables/test_dash_ag_grid.py
- vizro-core/tests/unit/vizro/tables/test_dash_table.py
Closes #486 
This PR is a quick demo of a couple new features in dcc.Loading available in dash 2.17. This is just to make it easier to see how it it might work in Vizro apps.
It adds 
- `delay_show=500` to reduce the flickering on short loading times
- `overlay_style={"visibility": "visible", "filter": "blur(2px)"}` as an example of styling the  background.
I'm interested to hear what you think!
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on …
> [Feat] Add new dcc.Loading features in dash 2.17

- .github/workflows/checks-vizro-ai.yml
- .github/workflows/checks-vizro-core.yml
- .github/workflows/lint-vizro-all.yml
- .github/workflows/test-integration-vizro-ai.yml
https://github.com/mckinsey/vizro/pull/480 altered the "new changelog fragment added" check slightly, and this made the check fail in #502. This PR fixes it.
In short, the crucial change that broke the check was that I had added `'` in the command:
```
git diff --name-only --diff-filter=A -r HEAD^1 HEAD -- changelog.d/*.md | xargs
git diff --name-only --diff-filter=A -r HEAD^1 HEAD -- 'changelog.d/*.md' | xargs
```
Actually adding `'` _was the correct thing to do_, and the fact that it worked correctly before was a bit of an accident and very difficult to understand why. The overall correct command is this, which has `'` and `--no-renames`:
```
git diff --name-only --no-renames --diff-filter=A -r HEAD^1 HEAD -- 'changelog.d/*.md' | xargs
```
Tidying up a bit, I've now changed the command …
> [CI] Fix changelog fragment check

- .github/workflows/checks-vizro-ai.yml
- .github/workflows/checks-vizro-core.yml
#503 swapped `xargs` for `cat` to be more readable, but that causes problems when sending the output to `GITHUB_OUTPUT` so I've changed that bit back.
- I have not referenced individuals, products …
> [CI] Fix changelog fragment check again

- vizro-ai/changelog.d/20240606_155107_anna_xiong_update_vizro_ai_integration_test.md
- vizro-ai/src/vizro_ai/_vizro_ai.py
- vizro-ai/tests/integration/test_example.py
Update `vizro-ai` integration test to use customized output `PlotOutputs` dataclass.
- `_return_all_text` private attributes is no longer needed and the output dictionary will be replaced by dataclass
for more details about the new feature please see #488 
- I certify that the use of this contribution as authorized by the Apache 2.0 license does …
> [Test] Update vizro ai integration test for dataclass output

- vizro-ai/.readthedocs.yaml
- vizro-ai/changelog.d/20240619_105033_antony.milne_fix_docs.md
- vizro-ai/hatch.toml
- vizro-core/.readthedocs.yaml
- vizro-core/changelog.d/20240619_102218_antony.milne_fix_docs.md
- vizro-core/hatch.toml
Pin `mkdocstrings-python<1.10.4` since 1.1.0.4 (and probably future versions) seems to break our docs build. See e.g. https://readthedocs.org/projects/vizro/builds/24734796/
```
WARNING -  mkdocs_autorefs: pages/API-reference/captured-callables.md: Could not find cross-reference target '[vizro.models.AgGrid]'
```
Probably this is to do with the first point here on their release notes: https://github.com/mkdocstrings/python/releases/tag/1.10.4.
I'll make a ticket to investigate further and unpin.
Also:
* Add `pip freeze` stage to docs builds to make debugging easier
* Cherrypick the `--ignore-url` change from [ea5cf95](https://github.com/mckinsey/vizro/pull/524/commits/ea5cf959d3ae17584fe1e95e1bc7a37c3e0fbfee) to merge it sooner because it's already blocking us
- I submit this contribution …
> [CI] Fix docs build

- .vale/styles/Microsoft/Acronyms.yml
- .vale/styles/Microsoft/Foreign.yml
- .vale/styles/Microsoft/Headings.yml
- CONTRIBUTING.md
- vizro-ai/changelog.d/20240621_124149_huong_li_nguyen_fix_vale.md
- vizro-ai/docs/pages/user-guides/add-generated-chart-usecase.md
- vizro-ai/docs/pages/user-guides/chart-examples.md
- vizro-core/changelog.d/20240621_124137_huong_li_nguyen_fix_vale.md
- vizro-core/docs/pages/explanation/contributing.md
- vizro-core/docs/pages/explanation/faq.md
- vizro-core/docs/pages/user-guides/custom-figures.md
- vizro-core/docs/pages/user-guides/data.md
- vizro-core/docs/pages/user-guides/layouts.md
- vizro-core/docs/pages/user-guides/parameters.md
- vizro-core/docs/pages/user-guides/table.md
- Fix all warnings and suggestion from `vale` that were not visible until an error was introduced
---
@stichbury - returning to your comment on why certain things were not raised on Vale in the last PRs. I just quickly checked, and there are two relevant factors:
- Previously, `e.g.` was considered an error, but `e.g` was not -> I've made it stricter in this PR now
- It seems like `vale` as a pre-commit hook will always return "passed" as long as there is no new error introduced (3 different levels: error, warning, suggestion). 
This means that over time, `vale` probably raised a couple of suggestions and warnings, but they were never shown to us unless we simultaneously introduced a `vale` error. To find all of the warnings/suggestions, I intentionally added an error (adding `e.g. this` …
> [Docs] Fix warnings and suggestions from `vale`

- vizro-ai/changelog.d/20240621_204959_lingyi_zhang_remove_langchain_community.md
- vizro-ai/hatch.toml
- vizro-ai/pyproject.toml
- vizro-ai/snyk/requirements.txt
- vizro-ai/tests/unit/vizro-ai/components/test_chart_selection.py
- vizro-ai/tests/unit/vizro-ai/components/test_code_validation.py
- vizro-ai/tests/unit/vizro-ai/components/test_custom_chart_wrap.py
- vizro-ai/tests/unit/vizro-ai/components/test_dataframe_craft.py
- vizro-ai/tests/unit/vizro-ai/components/test_explanation.py
- vizro-ai/tests/unit/vizro-ai/components/test_visual_code.py
`langchain` is not dependent on `langchain-community` anymore since v0.2, and `langchain-community` is not a dependency of vizro_ai.
https://github.com/langchain-ai/langchain/discussions/19083
- I …
> Remove unused dependency from vizro_ai

- vizro-core/changelog.d/20240626_165216_huong_li_nguyen_add_sign_kpi_card.md
- vizro-core/examples/_dev/app.py
- vizro-core/src/vizro/figures/kpi_cards.py
- vizro-core/tests/unit/vizro/figures/test_kpi_cards.py
- Improve `reference_format` of `kpi_card_reference` by showing + sign in case positive delta
- I …
> [Tidy] Improve `reference_format` of `kpi_card_reference`

- vizro-core/changelog.d/20240626_161742_petar_pejovic_fix_title_misalignment.md
- vizro-core/examples/_dev/app.py
- vizro-core/src/vizro/models/_components/table.py
- vizro-core/tests/unit/vizro/models/_components/test_table.py
- vizro-core/tests/unit/vizro/tables/test_dash_table.py
Reference -> https://github.com/McK-Internal/vizro-internal/issues/1102#issuecomment-2191735604
- …
> [Bug] Fix title disappearance when scrolling dash_data_table

- vizro-ai/changelog.d/20240627_003947_lingyi_zhang_use_basechatmodel.md
- vizro-ai/src/vizro_ai/chains/_llm_chain.py
- vizro-ai/src/vizro_ai/chains/_llm_models.py
- vizro-ai/src/vizro_ai/components/_base.py
- vizro-ai/src/vizro_ai/components/chart_selection.py
- vizro-ai/src/vizro_ai/components/code_validation.py
- vizro-ai/src/vizro_ai/components/custom_chart_wrap.py
- vizro-ai/src/vizro_ai/components/dataframe_craft.py
- vizro-ai/src/vizro_ai/components/explanation.py
- vizro-ai/src/vizro_ai/components/visual_code.py
- vizro-ai/src/vizro_ai/task_pipeline/_pipeline.py
- vizro-ai/src/vizro_ai/task_pipeline/_pipeline_manager.py
Motivation:
when adding optional model families, in current setting, LLM_MODELS value varies based on import result
```
try:
from langchain_anthropic import ChatAnthropic
except ImportError:
ChatAnthropic=None
if ChatAnthropic in not None:
LLM_MODELS = Union[ChatOpenAI, ChatAnthropic]
```
Use the parent class of all langchain supported chat models
Then we don't need this lines of code:
```
LLM_MODELS = Union[ChatOpenAI]
if ChatAnthropic in not None:
LLM_MODELS = Union[ChatOpenAI, ChatAnthropic]
```
- I certify that (a) this contribution is my original creation and / …
> [Tidy] Use BaseChatModel for type hint

- vizro-core/changelog.d/20240703_091955_huong_li_nguyen_fix_selector_return_type.md
- vizro-core/examples/_dev/app.py
- vizro-core/src/vizro/actions/_actions_utils.py
- vizro-core/src/vizro/models/_action/_action.py
- vizro-core/tests/unit/vizro/actions/conftest.py
- vizro-core/tests/unit/vizro/actions/test_parameter_action.py
Previously if you've specified the options of a selector as a `List[Dict]` inside a `Parameter`, the value was returned as a List[Dict] when "ALL" was selected (introduced by us), but would return a List of values only when selecting other values from the multi selector (dash default). This could lead to issues when using custom charts, as it's not immediately transparent for the user what the return type is, see https://github.com/mckinsey/vizro/issues/557. 
- Fixes inconsistent return types in selectors by always returning a List (similar to Dash)
FYI: @lingyielia @petar-qb @antonymilne 
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third …
> [Bug] Fix inconsistent return types in selector values

- vizro-core/changelog.d/20240708_105029_huong_li_nguyen_fix_default_nav_items.md
- vizro-core/examples/_dev/app.py
- vizro-core/src/vizro/models/_navigation/nav_bar.py
- Remove default icon provision for `vm.NavLink` when the icon count exceeds 9 and a user icon is provided
Before:
After:
- I have not referenced individuals, products or companies in any commits, …
> [Bug] Fix default icon provision for `vm.NavLink`

- .github/dependabot.yml
Went through the repository, and it seems that this was the only place where a label was automatically added. Removed that logic to be consistent with out current label system.
- I have not …
> [Tidy] Remove automatic label provision

- vizro-core/changelog.d/20240708_185435_huong_li_nguyen_enable_dynamic_option_height.md
- vizro-core/examples/_dev/app.py
- vizro-core/src/vizro/models/_components/form/dropdown.py
- vizro-core/tests/unit/vizro/models/_components/form/test_dropdown.py
- Update `optionHeight` of `vm.Dropdown` dynamically based on character length
- I have not added …
> [Feat] Update `optionHeight` of `vm.Dropdown` dynamically

- vizro-ai/changelog.d/20240703_171515_jo_stichbury_admonition_review.md
- vizro-ai/docs/pages/user-guides/install.md
- vizro-core/changelog.d/20240703_171525_jo_stichbury_admonition_review.md
- vizro-core/docs/pages/examples/examples.md
- vizro-core/docs/pages/explanation/documentation-style-guide.md
- vizro-core/docs/pages/tutorials/explore-components.md
- vizro-core/docs/pages/user-guides/actions.md
- vizro-core/docs/pages/user-guides/assets.md
- vizro-core/docs/pages/user-guides/card-button.md
- vizro-core/docs/pages/user-guides/container.md
- vizro-core/docs/pages/user-guides/custom-charts.md
- vizro-core/docs/pages/user-guides/custom-components.md
- vizro-core/docs/pages/user-guides/dashboard.md
- vizro-core/docs/pages/user-guides/graph.md
- vizro-core/docs/pages/user-guides/install.md
- vizro-core/docs/pages/user-guides/layouts.md
- vizro-core/docs/pages/user-guides/pages.md
- vizro-core/docs/pages/user-guides/parameters.md
- vizro-core/docs/pages/user-guides/run.md
- vizro-core/docs/pages/user-guides/selectors.md
- vizro-core/docs/pages/user-guides/table.md
Rationalisation of the admonitions used across core and vizro-ai docs.
* Removed or replaced any `tip` and `info` admonitions so we have just 4 types: 
* `warning` for explicit admonitions. Use these where the reader could make an error that causes them to waste time
* `example` the purple testube!
* `note` for asides that are things we want to call out or slight "asides" that fit better in a box (sometimes collapsed)
* `details` (used sparingly in the explanation page to hide lengthy text chunks that are more marketing than docs) 
* Removed any expanded-on-load collapsibles (or replaced with standard expanded versions). On the whole, I think we should avoid collapsibles unless there are lengthy chunks of code that not everyone needs to read, or there's a side note that doesn't really …
> [Docs] Rationalise admonitions in documentation

- vizro-core/changelog.d/20240716_091858_maximilian_schulz_try_out_link_target.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/models/_components/card.py
- vizro-core/tests/unit/vizro/models/_components/test_card.py
Previously when clicking `vm.Card` used as a `NavCard`, ie with `href` enabled, would lead to external links opening in the same tab, but not in a new tab, on py.cafe. This is now fixed.
Adding some more info (thanks @petar-qb ):
- More info on what `target="_blank"` does - [see link](https://www.w3schools.com/tags/att_a_target.asp)
- It looks from the docs that `dbc.NavLink` works out when to format links and when not: https://dash-bootstrap-components.opensource.faculty.ai/docs/components/nav/
P.S. It is debatable whether this is really a bug or a feature, but given that it broke things on py.cafe, I will leave the Bug tag - happy to have it changed though
P.P.S Based on @antonymilne new suggestion I changed the PR title to reflect the new approach - external links now open in the full …
> [Bug] External links for vm.Card now open in the full body

- vizro-core/changelog.d/20240718_151233_huong_li_nguyen_validation_error_captured.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/figures/kpi_cards.py
- vizro-core/src/vizro/models/_components/_form.py
- vizro-core/src/vizro/models/_components/container.py
- vizro-core/src/vizro/models/_components/tabs.py
- vizro-core/src/vizro/models/_models_utils.py
- vizro-core/src/vizro/models/_page.py
- vizro-core/src/vizro/models/types.py
- vizro-core/src/vizro/tables/_dash_ag_grid.py
- vizro-core/src/vizro/tables/_dash_table.py
- vizro-core/tests/unit/vizro/conftest.py
- vizro-core/tests/unit/vizro/models/_components/test_figure.py
- vizro-core/tests/unit/vizro/models/conftest.py
- vizro-core/tests/unit/vizro/models/test_models_utils.py
- Improve validation error if CapturedCallable is directly provided as a  `component`
- Context: https://github.com/mckinsey/vizro/issues/588
Thanks to @objectivitydrx for raising the bug and making a suggestion to improve our docs! 📝 🚀  …
> [Tidy] Improve validation error message if `CapturedCallable` is directly provided

- vizro-ai/changelog.d/20240730_121955_lingyi_zhang_fix_false_positive.md
- vizro-ai/tests/integration/test_example.py
This test often failed due to a false positive like this:
```
>       assert_that(
resp.business_insights,
any_of(
contains_string("GDP per capita in the United States"),
contains_string("GDP in the United States"),
contains_string("GDP in the US"),
),
)
E       AssertionError: 
E       Expected: (a string containing 'GDP per capita in the United States' or a string containing 'GDP in the United States' or a string containing 'GDP in the US')
E            but: was 'The code snippet generates a bar chart showing the composition of GDP per capita in the US over the years. It provides a visual representation of how GDP per capita has changed annually in the US.'
```
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that …
> [Bug] Fix a false positive in integration test

- .github/workflows/labeler.yml
- vizro-core/changelog.d/20240801_152834_huong_li_nguyen_fix_slider_type.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/schemas/0.1.20.dev0.json
- vizro-core/src/vizro/models/_components/form/_form_utils.py
- vizro-core/src/vizro/models/_components/form/range_slider.py
- vizro-core/src/vizro/models/_components/form/slider.py
- vizro-core/tests/unit/vizro/models/_components/form/test_range_slider.py
- vizro-core/tests/unit/vizro/models/_components/form/test_slider.py
Closes: https://github.com/mckinsey/vizro/issues/612: Previously, our marks were converted to integers, leading to incorrect value displays. This, combined with an existing bug in Dash, caused the marks to be displayed incorrectly.
- Fix typing inside `vm.Slider` and `vm.RangeSlider`
- Added a validator to consistently format floats to integers when possible, thus circumventing this Dash bug: https://github.com/plotly/dash-core-components/issues/159#issuecomment-380581043)
@nadijagraca - I noticed that we previously had the typing `marks: Optional[Dict[float, str]]`, but it was changed in this PR: https://github.com/mckinsey/vizro/issues/230. Do you remember the reason for this change? I couldn't reproduce the original bug that the PR fixes, so I'm uncertain if reverting to the original …
> [Bug] Fix display of marks in `vm.Slider` and `vm.RangeSlider`

- .github/workflows/vizro-qa-tests-trigger.yml
Small fix for vizro-qa tests trigger.
The problem occurred because it tried to trigger non-existent branch. By default it would trigger main branch and in the vizro-qa tests logic it will checkout appropriate branch.
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property …
> [CI] Trigger vizro-qa fix

- vizro-core/docs/pages/examples/your-examples.md
@stichbury - I wasn't sure where best to add it. It is a `vizro-ai` example. However, to create a separate examples page just for `vizro-ai` didn't make much sense to me, so I've added it where the other `vizro` user examples live. But let me know if you disagree.
- I certify that the use of this contribution as authorized by the Apache 2.0 …
> [Docs] Add user example to `examples` page

- vizro-ai/changelog.d/20240809_143321_lingyi_zhang_4o_mini.md
- vizro-ai/docs/pages/user-guides/customize-vizro-ai.md
- vizro-ai/src/vizro_ai/_llm_models.py
- vizro-ai/src/vizro_ai/dashboard/_graph/dashboard_creation.py
- vizro-ai/src/vizro_ai/dashboard/_response_models/layout.py
Did some quick experiments on dashboard tasks. 4o-mini can create simple dashboard. When requirements become complex, the dashboard generated doesn't look nice. 
Already noticed that 4o-mini performed consistently worse in 2 sub-tasks:
1. understand the "grid-template-areas" for layout plan
2. follow the instruction to give datasets unique names
It still worth adding it to the list though, because it's cheap and can perform simple dashboard tasks.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original …
> [Feat] Add 4o-mini to model list

- vizro-core/changelog.d/20240802_160643_antony.milne_no_more_global_theme.md
- vizro-core/docs/pages/user-guides/graph.md
- vizro-core/docs/pages/user-guides/themes.md
- vizro-core/src/vizro/_vizro.py
Just some quick edits to the docs for #615. This isn't meant to fully explain how everything works but just make sure everything in the docs is correct and up to date.
---
In future we should write more about these, and I'll make a separate ticket for that:
- Theme switching applies template to charts affecting `fig.layout.template` and nothing else
- How to modify vizro_dark/light themes e.g. to alter a colour (could do as dictionary assignment or maybe some clever merge)
- Arguments like `color_discrete_map` etc. specified in plots takes precedence over the templates
- Example of how `plotly.express` colours do not change between themes due to how theme switching works. Possible solutions:
- Recommended: use colours that work with both themes (how do users find these?)
- Advanced user: …
> [Docs] Remove setting of `pio.templates.default` on import 

- vizro-core/changelog.d/20240815_131933_huong_li_nguyen_update_template.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/models/_components/graph.py
- vizro-core/tests/unit/vizro/models/_components/test_graph.py
In the past, including a subtitle with the chart resulted in it being cut off, causing confusion. Two users have already reported this issue internally. To address it, we've been using a post-update call `fig.update_layout(title_pad_t=24)`
I wanted to discuss the possibility of permanently incorporating this solution into our `vm.Graph`. Directly encoding it into the template is challenging due to the way Plotly charts function. Any changes to the template disrupt the alignment between the graph and table titles, which is essential for the dashboard.
**Before:**
**After:**
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as …
> [Bug] Dynamically change `title_pad_t` inside `vm.Graph` if subtitle is provided

- vizro-core/changelog.d/20240820_192710_maximilian_schulz.md
- vizro-core/mkdocs.yml
Pin `ruff` in mkdocs plugin. This fixes the docs integration for the time being
- I have not added …
> [Fix] Hotfix py.cafe docs integration

- vizro-core/changelog.d/20240902_163350_huong_li_nguyen_fix_calc_dropdown_height.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/models/_components/form/dropdown.py
- vizro-core/tests/unit/vizro/models/_components/form/test_dropdown.py
- Fix dynamically calculated `optionHeight` for `Dropdown` if options are provided as dict
- Previously calculated didn't consider the input of dict, thus resulting in false row heights
- Added unit tests to reflect changes
**Before**
**After**
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate …
> [Bug] Fix dynamically calculated `optionHeight` for `Dropdown`

- .pre-commit-config.yaml
Prettier mirror repo which we are currently using is archived: https://github.com/pre-commit/mirrors-prettier
Changed prettier usage for pre-commit from mirror to hook.
- I have not referenced …
> [CI] Change prettier from mirror to hook

- vizro-core/changelog.d/20240911_164757_huong_li_nguyen_fix_plotly_dependency_issue.md
- vizro-core/hatch.toml
- vizro-core/src/vizro/_themes/_templates/template_dark.py
- vizro-core/src/vizro/_themes/_templates/template_light.py
Due to changes in our chart template from this PR https://github.com/mckinsey/vizro/pull/677, our latest vizro version `0.1.22` was not compatible with `plotly<5.24.0`.
This is fixed in this PR now by a conditional check. We currently need to ensure that both `map_style` and `mapbox` work. In the future `map_style` will replace `mapbox` but until then we should ensure compatibility with older plotly versions as well.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit …
> [Bug] Fix dependency issue due to template update

- vizro-core/docs/pages/tutorials/first-dashboard.md
- vizro-core/docs/pages/user-guides/assets.md
- vizro-core/docs/pages/user-guides/run.md
I think the suffixes were previously there because there was a hick-up where previously deleted projects were not visible on pyCafe. So, it automatically added that suffix when the name was the same. This seems to be fixed now, so we can remove the suffix. I've already made sure that the projects exist and will remove the duplicated projects on pyCafe after the merge.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original …
> [Docs] Remove redundant suffix from pyCafe links

- vizro-core/changelog.d/20240916_163947_antony.milne_plotly_dependency.md
- vizro-core/pyproject.toml
Following https://github.com/mckinsey/vizro/pull/699, I've added the same lower bound `plotly>=5.12.0` to our vizro package requirements. Given our explicit dependency on plotly this should really have always been there.
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property …
> [Tidy] Add lower bound for plotly version

- .github/workflows/vizro-qa-tests-trigger.yml
Link to the tests results can be found in every tests run here: https://github.com/mckinsey/vizro/actions/runs/10996907875
- I have not referenced individuals, products or companies in any commits, …
> [CI] Make vizro-qa tests url visible

- .devcontainer/devcontainer.json
When launching codespaces, got error
```
====================================== ERROR ====================================
2024-10-01 15:09:49.152Z: The following error occurred reading the devcontainer.json file - "Additional text encountered after finished reading JSON content: ]. Path '', line 29, position 0." Please see https://docs.github.com/en/enterprise-cloud@latest/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers#devcontainerjson for help configuring your file.
=================================================================================
```
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third …
> [Fix] Update devcontainer.json file

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/general-question.yml
- .vale/styles/Microsoft/Headings.yml
- .vale/styles/Microsoft/Terms.yml
- vizro-core/changelog.d/20241004_203832_47538780+LydiaPitts_750_PyCafe_fix.md
- vizro-core/docs/pages/explanation/authors.md
- vizro-core/docs/pages/tutorials/explore-components.md
- vizro-core/docs/pages/tutorials/first-dashboard.md
- vizro-core/docs/pages/user-guides/card-button.md
- vizro-core/docs/pages/user-guides/custom-components.md
- vizro-core/docs/pages/user-guides/custom-css.md
- vizro-core/docs/pages/user-guides/custom-figures.md
- vizro-core/docs/pages/user-guides/install.md
- vizro-core/docs/pages/user-guides/run.md
- vizro-core/examples/visual-vocabulary/pages/__init__.py
Fix for https://github.com/mckinsey/vizro/issues/750 "Correct all mentions of Py.Cafe"
- Updates reference from Py.Cafe to PyCafe to describe their organization
- Mantians references to https://py.cafe/ to talk about the site itself …
> [Docs] Update references from Py.Cafe to PyCafe

- vizro-core/changelog.d/20241004_162300_rilesdou_replace_underscores_css.md
- vizro-core/docs/pages/explanation/authors.md
- vizro-core/src/vizro/models/_components/container.py
- vizro-core/src/vizro/models/_components/form/_alert.py
- vizro-core/src/vizro/models/_components/form/date_picker.py
- vizro-core/src/vizro/models/_components/tabs.py
- vizro-core/src/vizro/models/_dashboard.py
- vizro-core/src/vizro/static/css/layout.css
- vizro-core/src/vizro/static/css/tabs.css
- vizro-core/tests/unit/vizro/models/_components/form/test_date_picker.py
- vizro-core/tests/unit/vizro/models/_components/test_container.py
- vizro-core/tests/unit/vizro/models/_components/test_tabs.py
- vizro-core/tests/unit/vizro/models/test_dashboard.py
Fix #722
Replaced underscores with dashes in all occurrences of `className=` (except for `className="vizro_dark"`)
Changed respective class names in css files
N/A
- I have not referenced …
> [Tidy] Replace underscores with dashes in classNames

- vizro-core/changelog.d/20241010_135707_antony.milne_double_loading.md
- vizro-core/changelog.d/new_fragment.md.j2
- vizro-core/src/vizro/models/_components/ag_grid.py
- vizro-core/src/vizro/models/_components/figure.py
- vizro-core/src/vizro/models/_components/graph.py
- vizro-core/src/vizro/models/_components/table.py
A special treat for @petar-qb to find when he's feeling better 😀 Probably the easiest optimisation we could have made. Thank you to him for spotting this horrible inefficiency that I had written in the code!
Functionally this is exactly the same as before. It's just better performing. Previously doing `kwargs.setdefault` always ran the `.load()` function. Now we only want to run it if it's strictly required (which in Vizro at the moment it actually never is, but I saw someone doing `graph()` the other day so they were using it, and maybe we will in future).
- I …
> [Fix] Remove double loading of data

- vizro-core/docs/pages/tutorials/explore-components.md
- vizro-core/docs/pages/tutorials/first-dashboard.md
- vizro-core/docs/pages/user-guides/install.md
Adding in a set of links to PyCafe documentation to point readers to it if they want more info about how to use PyCafe.
- I have not referenced individuals, products or companies in any commits, …
> [Docs] Add PyCafe documentation links

- .github/workflows/pycafe-dashboards-in-CI.yml
- tools/pycafe/create_pycafe_links.py
- vizro-core/examples/scratch_dev/app.py
> [CI] Allow external contributors to trigger PyCafe CI

- vizro-core/changelog.d/20241114_152933_antony.milne_cap_dash.md
- vizro-core/pyproject.toml
Normally we follow [advice to not upper bound a dependency](https://iscinumpy.dev/post/bound-version-constraints/) but this is one case where it's a good idea.
We just found out that Dash 3 is going to come out soon so best to be pre-emptive with this one.
I'll do a release once this is merged.
- I certify that the use of this contribution as …
> [Deps] Cap to dash<3

- vizro-ai/hatch.toml
- vizro-core/hatch.toml
Very small change that allows pre-releases to be installed in our CI environments.
This means e.g. if pydantic releases an alpha version that breaks something on our end then we'll know about it before they release the full version. …
> [CI] Allow pre-releases

- vizro-ai/hatch.toml
- vizro-core/hatch.toml
Revert changes of #893. Plotly just released 6.0.0rc0 and it breaks lots of our tests. Let's not use prereleases any more... …
> [CI] Do not use prereleases

- vizro-core/mkdocs.yml
As part of ticket 1377 on the internal repo.
Adding `CYb3cxosCgsN2QDQVaSGQpMQCesqpsGQ3oTM02NtvkY` as our tag to enable readthedocs to add it to our hosted docs for verification by Google search console.
- I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone …
> [Docs] Add search console tag for verification

- pyproject.toml
- vizro-ai/hatch.toml
- vizro-core/hatch.toml
The root cause of the problem with uv installer in our CI was lack of `pyproject.version` in the root `pyproject.toml`.
I've added dynamic version and it is working.
- I have not referenced …
> [QA] Dynamic version for root pyproject.toml

- vizro-core/changelog.d/20250115_123645_huong_li_nguyen_fix_removal_of_number_input.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/static/css/slider.css
- Ensure that the custom CSS for the Slider no longer interferes with the visibility of the spinner buttons in number inputs …
> [Bug] Fix appearance of spinner buttons in number input

- vizro-ai/changelog.d/20250115_002943_lingyi_zhang_bedrock_model_name_error.md
- vizro-ai/docs/pages/user-guides/customize-vizro-ai.md
- vizro-ai/hatch.toml
- vizro-ai/src/vizro_ai/_llm_models.py
- vizro-ai/src/vizro_ai/_vizro_ai.py
`_get_model_name` raises "Model name could not be retrieved" when used with AWS Bedrock, because `ChatBedrock` class doesn't have corresponding property for model name retrieval.
The proposed fix is to drop `_get_model_name` entirely to prevent similar mismatch from models we haven't used. Also, `_get_model_name` is not a necessary step. If there is a need to know the model name, we can explicitly call the property.
e.g.,
```
from langchain_anthropic import ChatAnthropic
llm = ChatAnthropic(
model="claude-3-5-sonnet-latest",
api_key = os.environ.get("ANTHROPIC_API_KEY"),
base_url= os.environ.get("ANTHROPIC_API_BASE")
)
llm.model
```
will render 'claude-3-5-sonnet-latest'
Before this bug is fixed, users could use `ChatBedrockConverse` instead of `ChatBedrock`. …
> [Bug] Fixed the Bedrock model name error

- .devcontainer/devcontainer.json
- .pre-commit-config.yaml
- .prettierignore
- .stylelintignore
Very minor tidy up to keep the top level of the repo clean: we can just specify these ignores in `pre-commit-config.yaml` rather than in their own top-level `ignore` files.
- I have not referenced …
> [Tidy] Move prettierignore and stylelintignore to pre-commit config

- vizro-ai/examples/dashboard_ui/assets/custom.css
- vizro-core/changelog.d/20250123_183556_huong_li_nguyen_fix_css_nav_links.md
- vizro-core/examples/dev/assets/css/custom.css
- vizro-core/examples/visual-vocabulary/assets/css/custom.css
- vizro-core/src/vizro/static/css/bootstrap_overwrites.css
With the latest Bootstrap theme, the NavLinks inside our NavBars were incorrectly colored. However, this is actually not an issue of the Bootstrap theme, as the CSS itself is correct.
The issue appears as with the usage of `dbc.NavBar`, the className ="navbar-light" is automatically attached to that component in both dark and light theme. We could probably fix this via callbacks, but I think the CSS fix is fine.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this …
> [Bug] Fix coloring of NavLinks inside NavBar

- vizro-ai/pyproject.toml
- vizro-core/changelog.d/20250129_112526_huong_li_nguyen_check_plotly_update.md
- vizro-core/pyproject.toml
- vizro-core/src/vizro/_themes/generate_plotly_templates.py
- vizro-core/src/vizro/_themes/vizro_dark.json
- vizro-core/src/vizro/_themes/vizro_light.json
- Remove the default `mapbox` setting from our templates.
- Ignore deprecation warnings inside our tests since they originate from the `plotly` template and not from our own templates.
Since our templates are now static files instead of being dynamically generated (see: https://github.com/mckinsey/vizro/pull/967), we no longer set any defaults for `map` and now also `mapbox`. These static templates need to be compatible with all versions of `plotly`. 
If we decide to stop supporting older versions of plotly where `map` is not yet supported, we can add a default for `map` in our templates again. I'll discuss this with A. when he returns. For now, let's remove the defaults as they were just a nice-to-have anyway.
- I submit this contribution under the [Apache 2.0 …
> [Tidy] Remove default for `mapbox` inside template

- vizro-core/changelog.d/20250206_203003_maximilian_schulz_add_type_bug.md
- vizro-core/src/vizro/models/_base.py
- vizro-core/tests/unit/vizro/models/test_base.py
There was a discrepancy between pydantic V1 and V2:
V1: you could have a discriminated union where the discriminator would have multiple options for choosing which model to coerce into: e.g. you could have `type = "card"` twice, and it would coerce into the last type added.
V2: In V2 the same situation would lead to an error that would say: `TypeError: Value 'card' for discriminator 'type' mapped to multiple choices`.
This situation does not arise that often, mostly in re-runs, or tests. We test for this now, and it is fixed.
Note: We are thus defining a DEFAULT behaviour, which is that the last added model takes precedence in discriminated unions.
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled …
> [Bug] Fix discriminator error when adding duplicate type model

- vizro-core/changelog.d/20250218_142411_petar_pejovic_fix_sending_empty_list_through_parameter.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/actions/_actions_utils.py
- vizro-core/tests/unit/vizro/actions/test_parameter_action.py
Fixes https://github.com/mckinsey/vizro/issues/1010
Currently on the main branch, if an empty value of the `vm.Dropdown(multi=True)` Parameter.selector is chosen, `[None]` value will be sent into its target. This behaviour is introduced in this PR https://github.com/mckinsey/vizro/pull/95.
P.S.
Mentioned PR (https://github.com/mckinsey/vizro/pull/95) actually handles a really great use-case. It enables `None` to be sent into Parameter target which is not possible in the plain dash app by using a `dcc.Dropdown` component. So, creating the following component in the plain dash app will raise and exception only because of the `{"label": "None", "value": None}` option. Options like `True`, `False` and others work correctly. :
```py
dcc.Dropdown(
id="dropdown",
options=[
{"label": "None", …
```
> [Bug] Fix sending an empty list through parameter

- .github/workflows/pycafe-dashboards.yml
- tools/pycafe/test_pycafe_links.py
- vizro-core/changelog.d/20250219_152011_maximilian_schulz_make_CI_check_fail_CI.md
> [Tidy] Make CI actually fail

- tools/pycafe/create_pycafe_links_comments.py
- tools/pycafe/pycafe_utils.py
- tools/pycafe/test_pycafe_links.py
- vizro-core/pyproject.toml
- vizro-core/tests/unit/vizro/integrations/kedro/test_kedro_data_manager.py
PyCafe CI testing would fail on release PRs due to a mismatch in versions. This should address this.
Sneaked in:
- remove test for `DataCatalog` in non-lower bound tests due to deprecation warnings. Still testing for it in lower bound. Since we don't expect developmnet on a deprecated feature this shoulld be ok
- I certify that the use of this …
> [CI] Fix PyCafe CI failure on release

- vizro-ai/pyproject.toml
- vizro-core/pyproject.toml
- main currently fails due to the latest release of pydantic v2.11.0 as they have deprecated several methods: https://github.com/pydantic/pydantic/releases/tag/v2.11.0
- Add temporary upper bound on pydantic for now (as otherwise lots of files need to change due to deprecated methods and currently potentially interfere with the actions V2 PR)
@maxschulz-COL - could you double-check the changes required to remove the upper bound and align with @antonymilne when to implement these such that it doesn't interfere with his PR?
- I certify that (a) this contribution is my …
> [Fix] Add temporary upper bound on pydantic

- vizro-core/changelog.d/20250405_130546_huong_li_nguyen_unset_card_heigth_width.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/static/css/flex.css
- Follow up PR to Flex
- We also need to unset the height / width of `Card` inside the Flexbox. The Card previously had a height/width of 100% set to fill out any grid-space. Inside the Flex layout, it should just take on the size of its content.
@l0uden  - could you add another screenshot test that covers these cases (see scratch-dev):
```
page6 = vm.Page(
title="Flex - row/wrap - unequal content - no width",
layout=vm.Flex(direction="row", wrap=True),
components=[vm.Card(text=generate_lorem_ipsum()) for i in range(6)],
)
page8 = vm.Page(
title="Flex - row/wrap - unequal content - same width",
layout=vm.Flex(direction="row", wrap=True),
components=[vm.Card(text=generate_lorem_ipsum(), extra={"style": {"width": "200px"}}) for i in range(6)],
)
```
- I submit this contribution under the …
> [Tidy] Unset height and width for Card inside Flex

- vizro-ai/pyproject.toml
- vizro-core/pyproject.toml
Thanks to @emilykl for pointing out in #974 that we don't need to ignore some plotly warnings any more. I removed a few others that are no longer relevant too.
- I have not referenced individuals, …
> [Tidy] Remove old pytest ignores

- vizro-core/changelog.d/20250409_100011_huong_li_nguyen_make_container_title_optional.md
- vizro-core/docs/pages/user-guides/container.md
- vizro-core/docs/pages/user-guides/tabs.md
- vizro-core/schemas/0.1.37.dev0.json
- vizro-core/src/vizro/models/_components/container.py
- vizro-core/src/vizro/models/_components/tabs.py
- vizro-core/src/vizro/models/_page.py
- vizro-core/tests/unit/vizro/models/_components/test_container.py
- vizro-core/tests/unit/vizro/models/_components/test_tabs.py
- Make `Container.title `optional by default.  
- Enforce` Container.title` as mandatory via a validator only when the `Container` is used within `Tabs`.
**Context:**
Previously, `Container.title` was required in all cases, similar to `Page.title.` However, unlike Page, `Container.title` is not necessary for the `path` generation. Instead, it should be optional, aligning with components like `Graph`, `Table`, and `AgGrid`, where a title is not displayed unless provided.  
With the introduction of the `Flex` layout, having to always provide a `Container.title` has become a bit of a hassle, especially since it often needs to be hidden with CSS when creating sections without titles. By making `Container.title` optional, we make things more flexible while still ensuring it's required when …
> [Tidy] Make `Container.title` optional

- vizro-ai/docs/index.md
- vizro-ai/docs/pages/explanation/faq.md
- vizro-ai/docs/pages/tutorials/quickstart-dashboard.md
- vizro-ai/docs/pages/user-guides/create-complex-dashboard.md
- vizro-ai/docs/pages/user-guides/run-vizro-ai-dashboard.md
- vizro-ai/mkdocs.yml
I propose to add this to the front page of Vizro-AI. (Edited to change it slightly based on @lingyielia's advice)
---
I have also added a slightly shorter note to every dashboard page of Vizro-AI docs, so readers hitting them see it, in case they don't enter via the front page. It says this:
> Vizro-AI has largely been replaced by [Vizro-MCP](https://github.com/mckinsey/vizro/blob/main/vizro-mcp/README.md) and only supports chart generation from version 0.4.0.
---
Thoughts? @lingyielia ? @maxschulz-COL ? @antonymilne ?
- I certify that (a) this contribution is my …
> [Docs] Add information note to Vizro-AI docs

- vizro-core/changelog.d/20250612_095418_nadija_ratkusic_graca_dropdown_height_in_containers.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/models/_components/form/dropdown.py
- vizro-core/src/vizro/models/_controls/_controls_utils.py
- vizro-core/src/vizro/models/_controls/filter.py
- vizro-core/src/vizro/models/_models_utils.py
- vizro-core/tests/unit/vizro/models/_components/conftest.py
- vizro-core/tests/unit/vizro/models/_components/form/test_dropdown.py
- vizro-core/tests/unit/vizro/models/_controls/conftest.py
- vizro-core/tests/unit/vizro/models/_controls/test_filter.py
closes https://github.com/McK-Internal/vizro-internal/issues/1846
Antony FYI: https://github.com/McK-Internal/vizro-internal/issues/1829
- we might want to reconsider moving this part of code to the selector, as part of your refactoring. 
Fixed dropdown height calculation when dropdown selector is used in containers 
- I certify that the use of …
> [Bugfix] Fixed dropdown height calculation in containers dropdown

- vizro-core/changelog.d/20250625_093858_90609403+huong-li-nguyen_fix_header_alignment.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/static/css/tiles.css
* We previously adjusted the text alignment for `figure-title`, `header`, and `footer` to ensure the info icon aligns properly with the title.
* However, this change caused markdown text within the `header` and `footer` to appear misaligned.
* This PR applies targeted alignment fixes to all three selectors, so both the icons and markdown content are correctly aligned.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original …
> [Bug] Fix text alignment in figure header and footer

- vizro-core/hatch.toml
- vizro-core/pyproject.toml
Closes https://github.com/McK-Internal/vizro-internal/issues/1544
Set `dash>=3.1.1` in `pyproject.toml` to include:
- https://github.com/plotly/dash/pull/3279
- https://github.com/plotly/dash/pull/3351
I tested all `vizro-core` example dashboards, along with various dynamic filters and data-frame parameters, to verify that everything functions correctly, and I haven't found any unexpected behaviours. 
This PR unblocks the following tickets:
- https://github.com/mckinsey/vizro/pull/1243
- https://github.com/McK-Internal/vizro-internal/issues/1342
- https://github.com/mckinsey/vizro/pull/1265 without the `show_in_url=True` restriction when it's done on the same page.
- https://github.com/McK-Internal/vizro-internal/issues/1356
- https://github.com/McK-Internal/vizro-internal/issues/1547
- …
> Set dash>=3.1.1 in pyproject.toml

- vizro-core/changelog.d/20250703_114236_petar_pejovic_fix_download_and_url_components_location.md
- vizro-core/examples/scratch_dev/app.py
- vizro-core/src/vizro/models/_page.py
Closes https://github.com/McK-Internal/vizro-internal/issues/1935
The scratch dev example did not work before these changes as predefined `vizro_url` and `vizro_download` were placed in the wrong place.  
Here's the PR that introduced components -> https://github.com/mckinsey/vizro/pull/1258
- I certify that the use of this contribution as …
> [Fix] Fix location of the vizro_url and vizro_download components so they work

- vizro-core/docs/pages/cheatsheet/cheatsheet.html
One line change to enable relative link to whichever version of docs the user is reading.
- I have …
> [Docs] Update cheatsheet to replace link to Vizro docs with relative link
